Refactor JMX resources to use Spring instead of custom prutsel
ibissource/iaf pull request #1063
Opened 2020-09-15 11:56 UTC by nielsm5

2020-09-15 13:22 UTC, gvanbrakel requested changes

2020-09-15 13:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/BasicAdapterServiceImpl.java
> +		adapter.configure();
Dat zal de super toch wel doen?

2020-09-15 13:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java
> +    private String version = Integer.toHexString(this.hashCode());
Hier mag toch wel een stukje commentaar bij

2020-09-15 15:21 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/configuration/BasicAdapterServiceImpl.java
> +		adapter.configure();
Ja dat dacht ik ook, gaan nu een aantal tests door kapot

2020-09-21 06:37 UTC, gvanbrakel requested changes

2020-09-21 06:37 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/BasicAdapterServiceImpl.java
> +public class BasicAdapterServiceImpl extends AdapterServiceImpl implements ApplicationContextAware, InitializingBean {
Laten we deze class JmxRegisteringAdapterService noemen, want dat is wat hij doet. Er is niks basics aan.

2020-09-21 07:36 UTC, gvanbrakel approved these changes

2020-09-21 07:37 UTC, merged