Run Ibis4Test within a Docker container
ibissource/iaf pull request #1080
Opened 2020-09-22 08:35 UTC by mhdirkse

2020-09-22 15:44 UTC, gvanbrakel requested changes

2020-09-22 15:44 UTC, gvanbrakel commented on test/docker/Dockerfile
> +FROM ubuntu:18.04
Waar heb je deze ubuntu voor nodig? Kan je niet gewoon starten met een tomcat image?

2020-09-22 15:44 UTC, gvanbrakel commented on test/docker/Dockerfile
> +RUN wget -O jtds-1.3.1.zip "http://www.java2s.com/Code/JarDownload/jtds/jtds-1.3.1.jar.zip"
Waar gebruik je jtds voor? Het is toch een MS SQL driver? En niet degene die we gebruiken?

2020-09-22 15:44 UTC, gvanbrakel commented on test/docker/Dockerfile
> +RUN echo "log.dir.match=/usr/local/tomcat/log/larvatest" >> conf/catalina.properties
log.dir.match moet je zetten op:
``log.dir.match=(?i)(([cd]:[\\\\/]temp)|(/usr/local/tomcat/log/larvatest))``

Het lijkt me niet nodig om file.separator.regex te zetten.

2020-09-22 15:44 UTC, gvanbrakel commented on test/docker/Dockerfile
> +COPY docker/ojdbc7.jar lib/ojdbc7.jar
Je hebt nu ojdb7.jar als hard coded library opgenomen, in plaats van dat het een maven dependency is.
Als het lastig is om deze file te downloaden van de oracle website, vanwege userid/password, dan kan je er ook voor kiezen om hem van een andere site te downloaden, zoals https://jar-download.com/

2020-09-22 15:44 UTC, gvanbrakel commented on test/docker/Dockerfile
> +RUN sed -i -e "s|localhost|${ORACLE_DB_IP}|g" work/iaf/META-INF/context.xml
Heb je ook geprobeerd of het ook werkt als je de localhost laat staan?
Als je database container ook op dezelfde machine draait als de ibis-container, dan zou dat toch moeten kunnen?

2020-11-06 11:25 UTC, mhdirkse commented
Inmiddels werk ik aan een andere pull request om ibis4test in een Docker container te draaien. Deze pull request is verouderd.

2020-11-06 11:25 UTC, closed without merging