Subproject test should produce a WAR that accesses the database on arbitrary IP address
ibissource/iaf pull request #1085
Opened 2020-09-23 16:28 UTC by mhdirkse

I tested this by checking that I can still run the tests in Eclipse. I also tested a command-line Maven build in which I adjust the database IP address.

I did not test this end-to-end, but I checked that context.xml was updated as I wanted. I also compared with a .war file that was created without this fix. I extracted the two .war files and did a WinDiff.

One thing struck me about the WinDiff output. There were a few .jar files that were different. These had nothing to do with this change. I think this is not relevant, but I hope that someone can confirm this. I can show the WinDiff result in a chat if necessary.

2020-09-23 16:53 UTC, gvanbrakel requested changes

2020-09-23 16:53 UTC, gvanbrakel commented on test/pom.xml
> +		<databaseIpAddress>localhost</databaseIpAddress>
Ik zou dit niet ``databaesIpAddress`` noemen, maar ``databaseHost``

2020-09-24 07:20 UTC, mhdirkse commented on test/pom.xml
> +		<databaseIpAddress>localhost</databaseIpAddress>
Gedaan.

2020-09-24 09:29 UTC, gvanbrakel approved these changes

2020-09-24 09:29 UTC, merged