Provide ability to follow exception forwards
ibissource/iaf pull request #1118
Opened 2020-10-02 08:40 UTC by alisihab

2020-10-02 12:05 UTC, gvanbrakel requested changes
The basics of the PR are good.
However, if you provide a test as 'Unzip', then you'll have to make a proper unzip test.
You could also choose to create a test of this functionality only, for instance using the Exception pipe.

2020-10-02 13:39 UTC, nielsm5 requested changes

2020-10-02 13:39 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
> +   Copyright 2013, 2020 Nationale-Nederlanden
`2020 WeAreFrank!`
Unless you made this in 2013?

2020-10-02 13:39 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
> +			throws PipeRunException {
I would personally prefer if this would be on 1 line..

2020-10-02 13:39 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
> +				long tsReceived = DateUtils.parseToDate((String) pipeLineSession.get(IPipeLineSession.tsReceivedKey), DateUtils.FORMAT_FULL_GENERIC).getTime();
This session value is a drama, as we would say in Dutch. I believe it's possible for it to be either a `Date` or a formatted timestamp. Please look [here](https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java#L930)  for more info!

2020-10-05 08:05 UTC, gvanbrakel commented
I see you placed the scenario01.properties and scenario02.properties inside the subdirectories scenario01 and scenario02. This is usually not done, so this might be confusing.

2020-10-06 15:47 UTC, gvanbrakel requested changes
One additional request: Could you document this feature in the javadoc of AbstractPipe?

2020-10-08 15:38 UTC, nielsm5 approved these changes

2020-10-08 15:52 UTC, nielsm5 approved these changes

2020-10-08 15:55 UTC, gvanbrakel approved these changes

2020-10-08 15:56 UTC, merged