Generic way to store ConfigurationWarnings
ibissource/iaf pull request #1147
Opened 2020-10-14 11:39 UTC by alisihab

2020-10-14 13:37 UTC, nielsm5 requested changes

2020-10-14 13:37 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java
> +			ConfigurationWarnings.add(log, "The class ["+ClassUtils.nameOf(this)+"] is used one or more times. Please change to ["+FixedQuerySender.class.getName()+"] to avoid potential SQL injections!");
Is it also possible to add the adapter name?

2020-10-14 13:37 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java
> +	private final String deprecationSuppressKey="warnings.suppress.deprecated";
Move this, as public final static, to ConfigurationWarnings so all warnings/keys are in 1 place.

2020-10-19 07:45 UTC, nielsm5 requested changes

2020-10-19 07:45 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java
> +	public static final String defaultValueSuppressKey = "warnings.suppress.defaultvalue";
Technically, final statics field names should be all uppercase

2020-10-19 07:46 UTC, nielsm5 approved these changes

2020-10-19 13:23 UTC, gvanbrakel approved these changes

2020-10-19 13:24 UTC, merged