Fix #1191 Close endless loop in JdbcUtil.warningsToXml()
ibissource/iaf pull request #1204
Opened 2020-10-26 14:32 UTC by gvanbrakel

2020-10-26 16:34 UTC, nielsm5 requested changes

2020-10-26 16:34 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
> +			PreparedStatement stmt = connection.prepareStatement(query);
Moet je stmt niet sluiten?

2020-10-26 16:34 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
> +						warnings=warnings.getNextWarning();
Moet hier een test voor komen?

2020-10-27 07:36 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
> +			PreparedStatement stmt = connection.prepareStatement(query);
Dank!

2020-10-28 09:05 UTC, nielsm5 approved these changes

2020-10-28 09:06 UTC, merged