Add button to display full openapi schema description
ibissource/iaf pull request #1269
Opened 2020-11-17 09:50 UTC by alisihab

Closes #1089

2020-11-17 16:22 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
> +				if(StringUtils.isNotEmpty(ref)){
Does this not break any tests? If not, we need to add them! It's important we also test what happens when there is no schema

2020-11-17 16:24 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/views/Webservices.html
> +								</tr>
I'm not sure if I like the idea of adding this 'endpoint' to the list, as technically it's not an api service... Maybe we can add a button in the `<div class="ibox-title">` bar or something?

2020-11-18 12:50 UTC, nielsm5 approved these changes

2020-11-19 17:02 UTC, gvanbrakel requested changes
Could you resolve the merge conflict and test? Please check for uriPattern with slash or not

2020-11-24 15:16 UTC, gvanbrakel approved these changes

2020-11-24 15:16 UTC, merged