Use log4j for logging configs
ibissource/iaf pull request #1273
Opened 2020-11-18 14:19 UTC by alisihab

2020-11-18 17:02 UTC, gvanbrakel requested changes

2020-11-18 17:02 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/logging/IbisConfigurationXmlLayout.java
> +public class IbisConfigurationXmlLayout extends IbisMaskingLayout {
Why do we need a special layout for this?

2020-11-24 15:15 UTC, gvanbrakel approved these changes

2020-11-25 11:51 UTC, nielsm5 approved these changes

2020-11-25 11:51 UTC, merged