Show a warning for transaction timeout
ibissource/iaf pull request #1274
Opened 2020-11-18 15:36 UTC by alisihab

In case the transaction timeout is greater than the maximum transaction timeout, will add a configuration warning to be shown in the console

2020-11-18 16:57 UTC, gvanbrakel requested changes

2020-11-18 16:57 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +					String maximumTransactionTimeout = Misc.getMaximumTransactionTimeout();
Could you please change Misc.getMaximumTransactionTimeout() and Misc.getSystemTransactionTimeout() in returning 'Integer' instead of 'String'?

2020-11-19 17:04 UTC, gvanbrakel approved these changes

2020-11-20 09:03 UTC, nielsm5 approved these changes

2020-11-20 09:03 UTC, merged