improve XSD generation compatibility
ibissource/iaf pull request #1289
Opened 2020-11-24 15:59 UTC by gvanbrakel

2020-11-24 17:08 UTC, nielsm5 requested changes

2020-11-24 17:08 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/senders/SenderSeries.java
> +	}
Eigenlijk voor het mooi, moet je de implementatie van de functie dan verplaatsen.

2020-11-25 07:26 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/senders/SenderSeries.java
> +	}
Ik snap niet wat je daarmee bedoelt.

2020-11-25 09:50 UTC, nielsm5 approved these changes

2020-11-25 09:50 UTC, merged