Fix #577 minor improvement while writing the lineseparator
ibissource/iaf pull request #1290
Opened 2020-11-25 10:57 UTC by alisihab

2020-11-25 15:20 UTC, gvanbrakel requested changes

2020-11-25 15:20 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/Misc.java
> +	 * If eof is specified, appends new line char after copying data.
it appends the bytes specified in eof, (that could represent a newline)

2020-11-25 16:05 UTC, gvanbrakel approved these changes

2020-11-27 10:01 UTC, nielsm5 approved these changes

2020-11-27 10:04 UTC, merged