Change JMX to use PlatformMBeanServer
ibissource/iaf pull request #1294
Opened 2020-11-25 15:36 UTC by nielsm5

Change Ibis change log-level endpoint to include IbisDataAdmin

2020-11-25 15:42 UTC, nielsm5 commented
See https://stackoverflow.com/questions/9592283/multiple-mbean-servers-found-spring-jmx-with-websphere-7 for more info regarding the two JMX MBeanServers

2020-11-25 15:43 UTC, nielsm5 commented
Fixes #1253

2020-11-26 07:22 UTC, gvanbrakel requested changes

2020-11-26 07:22 UTC, gvanbrakel commented on core/src/main/resources/AppConstants.properties
> +configurations.adapterService=nl.nn.adapterframework.configuration.JmxRegisteringAdapterService
Ik vind het eigenlijk geen goed idee dat we nu ons vastbinden op 'AdapterService'.
Kunnen we dit niet doen op basis van jmx.enabled=true of false?

2020-11-26 10:59 UTC, gvanbrakel approved these changes

2020-11-26 10:59 UTC, merged