Refactor stub4testtool.xsl
ibissource/iaf pull request #1311
Opened 2020-12-02 15:35 UTC by ricardovh

Refactors stub4testtool.xsl to enable the following items:
- Senders in senders (#674)
- Multiple receivers (#1102)

2020-12-02 15:38 UTC, ricardovh commented
Also implements #1195 (https://github.com/ibissource/iaf/pull/1195#discussion_r512685293 not included as pipes are not stubbed unless explicitly added).

2020-12-08 09:18 UTC, gvanbrakel requested changes

2020-12-08 09:18 UTC, gvanbrakel commented on core/src/main/resources/xml/xsl/stub4testtool.xsl
> +										or @className='nl.nn.adapterframework.http.rest.ApiListener']]">
Zou je hier een comment bij kunnen zetten dat deze Listeners als uitzondering niet gestubt worden, en alle overige wel?

2020-12-08 09:18 UTC, gvanbrakel commented on core/src/main/resources/xml/xsl/stub4testtool.xsl
> +	<xsl:template match="sender[   @className='nl.nn.adapterframework.jdbc.ResultSet2FileSender'
Zou je hier een comment bij kunnen zetten dat deze Senders als uitzondering niet gestubt worden, en alle overige wel?

2020-12-09 08:59 UTC, gvanbrakel approved these changes

2020-12-09 19:28 UTC, nielsm5 approved these changes

2020-12-10 07:52 UTC, merged