Fix #1256 configure receivers even if pipeline fails to configure
ibissource/iaf pull request #1331
Opened 2020-12-10 16:51 UTC by alisihab

Fixes #1256

2020-12-11 10:06 UTC, gvanbrakel approved these changes

2020-12-14 09:15 UTC, gvanbrakel requested changes

2020-12-14 09:15 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> +			throw new ConfigurationException("Exception configuring "+ ClassUtils.nameOf(pipe) +" ["+pipe.getName()+"]",t);
Could you check other locations where pipes are configured, like for validators and wrappers, to see the same extension to the exception message is made?

2020-12-14 10:53 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> +			throw new ConfigurationException("Exception configuring "+ ClassUtils.nameOf(pipe) +" ["+pipe.getName()+"]",t);
You just showed me it is already done!

2020-12-14 13:59 UTC, gvanbrakel approved these changes

2020-12-14 14:11 UTC, nielsm5 approved these changes

2020-12-14 14:12 UTC, merged