Fix #1272, #488 browse jdbc table for different databases
ibissource/iaf pull request #1377
Opened 2021-01-07 16:45 UTC by alisihab

2021-01-07 17:38 UTC, gvanbrakel requested changes

2021-01-07 17:38 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseJdbcTable.java
> +						}
Would it be possibe to use descriptive constants or column names, instead of '4', '5' and '7'?

2021-01-11 07:20 UTC, gvanbrakel approved these changes

2021-01-11 08:50 UTC, nielsm5 approved these changes

2021-01-11 08:51 UTC, merged