Refactor adapter ibisstore implementation
ibissource/iaf pull request #1404
Opened 2021-01-19 13:03 UTC by alisihab

2021-01-20 09:56 UTC, nielsm5 requested changes

2021-01-20 09:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/js/config.js
>  		url: "/adapter/:adapter/:receiver/",
Could you rename this to `/adapter/:adapter/receiver/:receiver/` the the url is somewhat api compliant?

2021-01-20 09:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/js/controllers.js
> +	$state.$current.data.breadcrumbs = "Adapter > "+$state.params.storageType;
Can you not do this in the config.js like it's done for `pages.storage.view` ?

2021-01-20 09:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/js/controllers.js
> +			return JSON.parse(sessionStorage.getItem('DataTable'+$scope.storageType));
This should be `return filterCookie`;

2021-01-20 09:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/js/controllers.js
> +			sessionStorage.setItem('DataTable'+$scope.storageType, JSON.stringify(data));
This should be `Cookies.set($scope.storageType+"Filter", data);`

2021-01-20 09:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html
> +									<td><input disabled icheck type="checkbox" ng-change="updateFilter('id', storageType)" ng-model="displayColumn.id"/></td>
I don't think you need to pass the storageType here, as it's already present as a `$scope.storageType` variable in the controller.

2021-01-21 10:04 UTC, nielsm5 approved these changes

2021-01-22 08:21 UTC, gvanbrakel approved these changes

2021-01-22 08:21 UTC, merged