Refactor getResourceURL(Object/Class)
ibissource/iaf pull request #1409
Opened 2021-01-21 14:35 UTC by nielsm5

2021-01-22 08:13 UTC, gvanbrakel requested changes

2021-01-22 08:13 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/classloaders/ClassLoaderBase.java
> +			return null;
Moet je dan niet toch ergens een warning geven?

2021-01-22 08:13 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/ClassUtils.java
> +	public static URL getResourceURL(ClassLoader classLoader, String resource) {
Hier had ik nu een IConfigurationClassLoader als argument verwacht, toch?

2021-01-24 14:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/ClassUtils.java
> +	public static URL getResourceURL(ClassLoader classLoader, String resource) {
Dan moet er te veel aangepast worden, en het levert relatief weinig op.

2021-02-01 16:25 UTC, gvanbrakel requested changes
Ik vind het een verbetering!
'IHasConfigurationClassLoader`` zou ik denk ik ``ConfigurationItem`` genoemd hebben,
en ``classLoaderProvider`` dan ``base``, omdat het niet om het class loaden gaat, maar om een startpunt om resources te laden.

2021-02-01 16:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/core/ResourceTest.java
> +	private IHasConfigurationClassLoader getBytesClassLoader() throws IOException, ConfigurationException {
Dit wordt dan getBytesClassLoaderProvider()

2021-02-01 16:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/util/ClassUtilsTest.java
> +	private IHasConfigurationClassLoader nullClassLoader = null;
dit wordt dan ``nullClassLoaderProvider``

2021-02-01 16:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/util/ClassUtilsTest.java
> +	private IHasConfigurationClassLoader getBytesClassLoader() throws IOException, ConfigurationException {
dit wordt dan ``getBytesClassLoaderProvider()``

2021-02-01 16:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/validation/ValidatorTestBase.java
> +	private IHasConfigurationClassLoader testClassLoader = new ClassLoaderProvider();
Dit wordt dan ``testClassLoaderProvider``

2021-02-01 16:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/xml/ClassLoaderEntityResolverTest.java
> +	private IHasConfigurationClassLoader localClassLoader = new ClassLoaderProvider();
dit wordt dan ``localClassLoaderProvider``

2021-02-02 10:41 UTC, nielsm5 commented on aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java
> +			URL licenseUrl = ClassUtils.getResourceURL(license);
Ik denk het niet, een licentie moet je 1x ergens op het classpath oid zetten, en niet per configuratie

2021-02-02 11:05 UTC, gvanbrakel approved these changes

2021-02-02 15:21 UTC, merged