Replace proxiedDataSources with DataSourceFactory
ibissource/iaf pull request #1415
Opened 2021-01-22 16:58 UTC by gvanbrakel

2021-02-01 09:48 UTC, nielsm5 requested changes

2021-02-01 09:48 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/DomainTransformerPipe.java
> -		qs.setProxiedDataSources(proxiedDataSources);
Soms geef je hem mee, en soms haal je het weg?

2021-02-01 09:48 UTC, nielsm5 commented on core/src/main/resources/springTOMCATBTM.xml
> -		<property name="lookupOnStartup" value="${jdbc.required}"/>
Ik zie dat je een `LazyConnectionDataSourceProxy` gebruikt, heeft dat het zelfde effect?

2021-02-01 11:07 UTC, gvanbrakel commented on core/src/main/resources/springTOMCATBTM.xml
> -		<property name="lookupOnStartup" value="${jdbc.required}"/>
Nee, maar wel net zoiets: het vraagt pas een connectie op bij de driver als er een statement gecreerd wordt.

2021-02-01 11:08 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/DomainTransformerPipe.java
> -		qs.setProxiedDataSources(proxiedDataSources);
Deze kan weg, omdat deze bean geAutowired wordt

2021-02-02 10:23 UTC, nielsm5 requested changes

2021-02-02 10:23 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/JdbcFacade.java
> +//			}
Mag dit weg?

2021-02-02 13:59 UTC, nielsm5 approved these changes

2021-02-02 13:59 UTC, merged