Change level for 4xx status code related log lines ApiListener
ibissource/iaf pull request #1437
Opened 2021-02-04 15:25 UTC by alisihab

Closes #1325

2021-02-05 07:28 UTC, gvanbrakel requested changes

2021-02-05 07:28 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +							if(log.isTraceEnabled()) log.trace(createAbortingMessage(remoteUser,304) + "matched if-none-match ["+ifNoneMatch+"]");
I would suggest this to be on debug level

2021-02-08 08:54 UTC, nielsm5 requested changes

2021-02-08 08:54 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +	public static final String AUTHENTICATION_COOKIE = "authenticationToken";
I think this should be `AUTHENTICATION_COOKIE_NAME`

2021-02-08 08:54 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +		log.info(infoMessage);
This can be wrapped in a 'isInfoEnabled', and perhaps even in a single line

2021-02-08 15:56 UTC, nielsm5 approved these changes

2021-02-08 16:21 UTC, gvanbrakel approved these changes

2021-02-09 06:11 UTC, aimiebell commented on core/src/main/java/nl/nn/adapterframework/webcontrol/action/BrowseJdbcTable.java
> +				browseJdbcTableForm.set("jmsRealm", cs.Value("jmsRealm"));
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:11 UTC, aimiebell commented on core/src/main/java/nl/nn/adapterframework/webcontrol/action/BrowseQueue.java
> +				browseQueueForm.set("jmsRealm",	       cs.Value("jmsRealm"));
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:11 UTC, aimiebell commented on core/src/main/java/nl/nn/adapterframework/webcontrol/action/ExecuteJdbcQuery.java
> +				executeJdbcQueryForm.set("jmsRealm", cs.Value("jmsRealm"));
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:11 UTC, aimiebell commented on core/src/main/java/nl/nn/adapterframework/webcontrol/action/SendJmsMessage.java
> +                sendJmsMessageForm.set("jmsRealm", cs.Value("jmsRealm"));
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 08:39 UTC, merged