Display user in gui
ibissource/iaf pull request #1446
Opened 2021-02-08 13:36 UTC by alisihab

Closes #1382

2021-02-08 16:56 UTC, nielsm5 requested changes

2021-02-08 16:56 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/views/common/topnavbar.html
> +            <li ng-if="::userName">{{::userName}}
I think the if statement should remain, the logout button is not directly related to the user. 
You can display the username here, when available of course :)

2021-02-09 15:18 UTC, nielsm5 approved these changes

2021-02-09 17:06 UTC, gvanbrakel approved these changes

2021-02-09 17:06 UTC, merged