#1233 Receiver and ErrorStorage
ibissource/iaf pull request #1450
Opened 2021-02-09 10:32 UTC by gvanbrakel

2021-02-15 15:56 UTC, gvanbrakel reviewed
The Issue also requests the option to have the number of message that is browsed to be increased to 1000. Did you address that too?

2021-02-15 15:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +	@Path("/adapters/{adapterName}/receivers/{receiverName}/errorstorage/changeProcessState")
Now this only works for errorStorage.
If a Hold storage is introduced (which is as simple as adding a statusValueHold attribute to a JdbcTableListener), then it should be possible to move messages from errorStorage to Available and to Hold, but also from Hold to Error.
I would expect the path to be something like:
``@Path("/adapters/{adapterName}/receivers/{receiverName}/storage/{processState}/changeto/{targetState}")``

2021-02-15 15:56 UTC, gvanbrakel commented on webapp/src/main/webapp/iaf/gui/js/controllers.js
> +			$scope.addNote("success", "Successfully moved messages to Available");
'Available' should reflect the targetState

2021-02-15 15:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +		IMessageBrowser<?> errorStorageBrowser = receiver.getMessageBrowser(ProcessState.ERROR);
browser to be retrieved must be selected by path variable

2021-02-15 15:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +		ProcessState targetState = ProcessState.valueOf(resolveStringFromMap(input, "targetState"));
targetState to be selected via path (or other input parameter)

2021-02-19 07:50 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/ProcessState.java
> +	String type=null;
Could you comment briefly on what 'type' means/ is used for

2021-02-19 07:50 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/ProcessState.java
> +	}
You could replace these getters and setters with Lombok field annotations ``@Getter`` and ``@Setter``

2021-02-19 07:50 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +				if(!receiver.changeProcessState(store.browseMessage(messageIds[i]), ProcessState.getProcessStateFromName(targetState), null)) {
You must check that targetState is really in the receiver.targetStates

2021-02-19 13:01 UTC, nielsm5 requested changes

2021-02-19 13:01 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
> +                                            <td>{{::pipes.sender}}<span ng-if="pipes.destination"> ({{::pipes.destination|truncate:150}})</span></td>
Kan je ook `title='{{pipes.destination}}'` toevoegen zodat men bij een 'on-hover' alles ziet?

2021-02-22 08:00 UTC, gvanbrakel reviewed
I would like to suggest to improve the layout of the message browsers on screen:
- have 'select all'/'deselect all' as a checkbox in the header, aligned with the individual selection checkbox;
- have the actions (e.g. 'delete', 'view', 'move to available', 'move to Hold') as small icons on the right side
- use arrow icons for the 'move to' actions, to the left for a move to a 'lower' process state, to the right for the move to a 'higher' process state

2021-02-22 08:00 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/ProcessState.java
> +		Map<ProcessState, Set<ProcessState>> targetProcessStates = new LinkedHashMap<>();
Turning this into a LinkedHashMap suggests that the insertion order is significant. Is that the case? Are there iterations over this map that should be in the right order?

2021-02-22 08:00 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +	private Map<ProcessState,Set<ProcessState>> targetProcessStates = new LinkedHashMap<>();
Turning this into a LinkedHashMap suggests that the insertion order is significant. Is that the case? Are there iterations over this map that should be in the right order?

2021-02-22 11:23 UTC, nielsm5 approved these changes

2021-02-22 11:52 UTC, merged