Limit eligibility to have wsdl
ibissource/iaf pull request #1508
Opened 2021-02-23 10:45 UTC by alisihab

Closes #1463

2021-02-23 12:09 UTC, gvanbrakel requested changes

2021-02-23 12:09 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/soap/WsdlUtils.java
> +		boolean haveWebServiceListener = false;
correct English would be 'hasWebServiceListener'

2021-02-23 12:09 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java
> +					Wsdl wsdl = new Wsdl(adapter.getPipeLine());
I think it is wise to add a TODO comment here, stating that Wsdl generation should be done on demand, not beforehand.

2021-02-24 07:21 UTC, gvanbrakel submitted a review, later dismissed

2021-02-24 17:04 UTC, gvanbrakel approved these changes
It appeared that I caused the Wsdl errors myself. Sorry for accusing you...
They have been fixed anyway!

2021-02-26 12:50 UTC, nielsm5 approved these changes

2021-02-26 12:51 UTC, merged