Frank!Doc: List allowed values for attributes based on enums in Java code
ibissource/iaf pull request #1555
Opened 2021-03-09 17:45 UTC by mhdirkse

2021-03-10 08:10 UTC, gvanbrakel approved these changes

2021-03-10 13:23 UTC, nielsm5 requested changes

2021-03-11 09:04 UTC, mhdirkse commented on core/src/test/resources/doc/examplesExpected/simple.json
> +          "restrictingType": "nl.nn.adapterframework.doc.testtarget.examples.simple.MyEnum"
Bij elementen van groepen hebben we ook verwijzingen. Een groep geeft zijn members door volledige class namen te geven (nl.nn....). Om de members van een groep weer te geven heb je echter de simple name nodig. Die moet bepaald worden door het element op te zoeken met de volledige naam als sleutel. Dat element bevat dan de simple name. In dit geval moet het zo om de JSON klein te houden.

De lijst van mogelijke waardes van een FrankAttribute kan gemeenschappelijk zijn met andere FrankAttribute objecten. Zo'n lijst wordt bepaald door een enum in de FF! Java code. Dezelfde enum kan op verschillende plaatsen gebruikt worden in een enum getter. We doen hieraan recht door naar types te verwijzen in plaats van de waardes direct op te nemen.

2021-03-11 09:31 UTC, mhdirkse commented on core/src/main/java/nl/nn/adapterframework/doc/model/FrankDocModel.java
> +	List<FrankAttribute> createAttributes(Method[] methods, FrankElement attributeOwner, Map<String, Method> enumGettersByAttributeName) throws ReflectiveOperationException {
Gedaan.

2021-03-11 09:32 UTC, mhdirkse commented on core/src/main/java/nl/nn/adapterframework/doc/model/FrankAttribute.java
> +	private @Getter @Setter AttributeValuesList attributeValuesList;
Gedaan.

2021-03-11 09:33 UTC, mhdirkse commented on core/src/main/java/nl/nn/adapterframework/doc/model/AttributeValuesList.java
> +public class AttributeValuesList {
Gedaan.

2021-03-11 09:57 UTC, mhdirkse commented on core/src/test/resources/doc/examplesExpected/simple.json
> +          "restrictingType": "nl.nn.adapterframework.doc.testtarget.examples.simple.MyEnum"
Ik heb de attribute values er direct in gezet, geen referenties meer daarvoor.

2021-03-11 10:08 UTC, nielsm5 approved these changes

2021-03-11 10:11 UTC, merged