Add unit tests for stats log filename
ibissource/iaf pull request #1573
Opened 2021-03-15 11:15 UTC by alisihab

2021-03-16 09:41 UTC, nielsm5 requested changes

2021-03-16 09:41 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/util/FileUtilsTest.java
> +		File tempDir = FileUtils.createTempDir();
I think it's safer to use a `TemporaryFolder` (junit thingie)
It creates a folder which is test independent. So you can create files etc without affecting other tests.
Have a look at the DirectoryListenerTest, it's used there.

2021-03-16 11:18 UTC, nielsm5 approved these changes

2021-03-17 10:00 UTC, gvanbrakel approved these changes

2021-03-17 10:00 UTC, merged