Introduce removeNonEmptyDirectory attribute for file systems
ibissource/iaf pull request #1591
Opened 2021-03-18 12:59 UTC by alisihab

2021-03-22 10:47 UTC, gvanbrakel requested changes

2021-03-22 10:47 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
> +	public void setRemoveNonEmptyDirectory(boolean removeNonEmptyDirectory) {
Please use 'Folder' instead of 'Directory'

2021-03-22 10:47 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
> +	public void fileSystemActorRmNonEmptyDirActionTest() throws Exception {
You should also test that if removeNonEmptyDirecty=false, that an exception is thrown if the folder is not empty.

2021-03-22 13:58 UTC, gvanbrakel approved these changes

2021-03-25 15:18 UTC, nielsm5 approved these changes

2021-03-25 15:19 UTC, merged