Wrapper api doclet
ibissource/iaf pull request #1626
Opened 2021-03-29 19:20 UTC by mhdirkse

At this stage, you can get the XSDs and the JSON as follows:

* Do `mvn clean install` in the checkout directory of the iaf.
* Go to the `frankDoc` subdirectory.
* Do `mvn -PfrankDoc site`

The unit-tests for the run-time generation of the files may be broken at the moment.

2021-03-30 08:04 UTC, mhdirkse commented
The tests of DocWriterNewIntegrationTest.java still work. These test the old way of running Frank!Doc using reflection. These tests can be run from Eclipse. Then the logging appears in the Console window of Eclipse. The resulting output files have the same size as before, not the smaller sizes observed from a doclet.

2021-04-08 16:39 UTC, mhdirkse commented
You can get the XSDs and the JSON as follows:

* Do `mvn -Pjavadoc clean install` in the checkout directory of the iaf.
* Go to the frankDoc subdirectory.
* Do `mvn -PfrankDoc site`

The unit tests have been fixed.

2021-04-09 07:21 UTC, gvanbrakel requested changes

2021-04-09 08:01 UTC, mhdirkse commented on frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/model/ElementType.java
> +				log.warn("Programming error, expected to be working with interfaces instead of classes", e);
Toen ik dit onderzocht bleek dat de exception helemaal niet gegooid hoeft te worden. Hij is hier weg.

2021-04-09 09:54 UTC, mhdirkse commented on core/pom.xml
> +				</configuration> </execution> </executions> </plugin> -->
Ik heb alle betekenisloze veranderingen weggehaald. Hierop heb ik de hele pull request gechecked.

2021-04-09 09:56 UTC, mhdirkse commented
Ik heb de pull request weer draft gemaakt. Ik zou hem graag integratie testen voordat we mergen. Het is bewerkelijk om dat na iedere kleine commit te doen. Mijn voorstel is dat jullie doorgaan met reviewen. Als de review klaar is, dan zal ik nog enkele testjes doen en dan zal ik de pull request terugzetten naar ready-for-review.

2021-04-13 11:06 UTC, gvanbrakel approved these changes

2021-04-13 11:16 UTC, nielsm5 approved these changes

2021-04-13 11:17 UTC, merged