Fix #1654 Byte array support for SOAPProviderBase
ibissource/iaf pull request #1662
Opened 2021-04-06 08:12 UTC by gvanbrakel

2021-04-06 09:54 UTC, nielsm5 approved these changes

2021-04-07 09:06 UTC, nielsm5 commented on ladybug/src/main/java/nl/nn/ibistesttool/PipeLineSessionDebugger.java
> +	}
Is het niet makkelijker om de PipeLineSessionBase te extenden en alleen de put methode te overriden?

2021-04-07 09:07 UTC, nielsm5 requested changes

2021-04-07 09:07 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/IPipeLineSession.java
> +	public Message getMessage(String key);
Dan heb ik liever dat je dit veranderd naar: 
```

	public default Message getMessage(String key) {
		Object obj = get(key);
		if(obj != null) {
			return Message.asMessage(obj);
		}
		return Message.nullMessage();
	}
```

2021-04-07 14:05 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/IPipeLineSession.java
> +	public Message getMessage(String key);
en waarom dan?

2021-04-07 15:22 UTC, nielsm5 approved these changes

2021-04-07 15:22 UTC, merged