Create PropertyResolvingXmlFilter
ibissource/iaf pull request #1686
Opened 2021-04-08 15:06 UTC by nielsm5

2021-04-29 16:25 UTC, gvanbrakel requested changes

2021-04-29 16:25 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/digester/AttributeCheckingRule.java
> +import nl.nn.adapterframework.util.LogUtil;
Deze class is eigenlijk niet veranderd

2021-04-29 16:25 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
> +	private boolean equals(Object dv, String value) {
wat is ``dv``? digestedValue? defaultValue?

2021-04-30 13:51 UTC, gvanbrakel approved these changes

2021-04-30 14:07 UTC, merged

2021-04-30 15:27 UTC, nielsm5 commented
See #1760