Fix #1685 change fileName attributes to filename
ibissource/iaf pull request #1699
Opened 2021-04-13 07:42 UTC by alisihab

Closes #1685

2021-04-13 08:44 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/errormessageformatters/FixedErrorMessage.java
> +		this.filename = fileName;
it's better to call the setter :)

2021-04-13 08:44 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/ResultSet2FileSender.java
> +		this.filenameSessionKey = filenameSessionKey;
its better to call the new setter

2021-04-13 10:56 UTC, gvanbrakel requested changes
It would also be good to make a note of this change in RELEASES.MD

2021-04-13 10:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/FilePipe.java
> +	public void setFilenameSessionKey(String filenameSessionKey) {
You should keep the old setter too, like setFileName()

2021-04-13 10:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
>  	public String getStubFileName() {
Rename this one too, or replace with ``@Getter``

2021-04-13 15:11 UTC, alisihab commented
> It would also be good to make a note of this change in RELEASES.MD

I am not sure about it since we show configuration warning(deprecation notice) in the console.

2021-04-15 07:10 UTC, gvanbrakel approved these changes

2021-04-16 08:15 UTC, nielsm5 approved these changes

2021-04-16 08:15 UTC, merged