Store SOAPAction in a session key
ibissource/iaf pull request #1705
Opened 2021-04-13 15:09 UTC by alisihab

Closes #1673

2021-04-13 15:54 UTC, gvanbrakel requested changes
Could you add a unit test or iaf-test to prove the behavior?

2021-04-15 07:06 UTC, gvanbrakel approved these changes

2021-04-16 09:54 UTC, nielsm5 requested changes

2021-04-19 08:50 UTC, nielsm5 requested changes

2021-04-19 08:50 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
> +	private String findAction(int start, String contentType) {
You could determine the start index in this method
`contentType.indexOf("action=")`

2021-04-19 08:50 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderTest.java
> +	}
All these tests could also be simplified by just testing `findAction(contentType)` with all these different contentTypes.
I would much rather see a test with soap1.1 and a soap 1.2 header, and vice-versa.
Happy flow vs unhappy flow

2021-04-19 08:50 UTC, nielsm5 commented on test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSender.xml
> +			<exits>
I think now that we have junit tests these are no longer required. Maybe its better to remove them

2021-04-21 08:12 UTC, nielsm5 approved these changes

2021-04-21 08:24 UTC, merged