QueryType string to enum
ibissource/iaf pull request #1709
Opened 2021-04-15 11:16 UTC by alisihab

Closes #1637

2021-04-16 06:35 UTC, gvanbrakel requested changes

2021-04-16 06:35 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
> +				QueryType.UPDATEBLOB==getQueryTypeEnum() && StringUtils.isEmpty(getBlobSessionKey());
When you compare strings to a fixed value, usually the fixed value is on the left side: ``"updateClob".equalsIgnoreCase(getQueryType())``
When testing enums, it is easier to read it the other way round:
 `` getQueryTypeEnum()==QueryType.UPDATECLOB``

2021-04-16 06:35 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
> +		OTHER,
Itn't this a comma too many?

2021-04-16 12:02 UTC, gvanbrakel requested changes

2021-04-16 12:02 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
> +					break;
It is a good practice to 'do' something here, like:
- comment or print a log line that this case is expected and does not need special handling
- throw an IllegalStateException, if this case should not be possible. That helps to fix problems when OutputTypes change over the years

2021-04-16 15:24 UTC, gvanbrakel approved these changes

2021-04-17 11:56 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/util/LockerTest.java
> +import nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.QueryType;
Do you use this import anywhere?

2021-04-17 11:56 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java
> +	public QueryType getQueryTypeEnum() {
This method doesn't require the Enum suffix?

2021-04-17 11:56 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java
>  	}
Is this method used anywhere? Isn't it easier to pass the Enum?

2021-04-19 08:51 UTC, nielsm5 approved these changes

2021-04-19 08:52 UTC, merged