Make output paths of FrankDoc files configurable
ibissource/iaf pull request #1715
Opened 2021-04-15 16:02 UTC by mhdirkse

2021-04-17 12:05 UTC, nielsm5 requested changes

2021-04-17 12:05 UTC, nielsm5 commented on frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/front/FrankDocletOptions.java
> +			throw new InvalidDocletOptionsException("Programming error. Switch over FrankDocletOptions.Option was supposed to cover all cases");
Ik denk dat je hier beter een IllegalArgumentException kan gebruiken

2021-04-19 08:21 UTC, mhdirkse commented on frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/front/FrankDocletOptions.java
> +			throw new InvalidDocletOptionsException("Programming error. Switch over FrankDocletOptions.Option was supposed to cover all cases");
Gedaan.

2021-04-20 13:08 UTC, gvanbrakel approved these changes

2021-04-21 08:23 UTC, nielsm5 approved these changes

2021-04-21 08:23 UTC, merged