JWT encode and decode pipes
ibissource/iaf pull request #1720
Opened 2021-04-16 13:45 UTC by ricardovh

2021-04-16 15:22 UTC, gvanbrakel requested changes
Je hebt nu een encode en een decode pipe gemaakt. In dergelijke gevallen hebben we meestal/liever één pipe met een directon- of action- attribuut. Dat beperkt de lijst van Pipes. Heb je dat nu bewust niet gedaan?

2021-04-16 15:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/JWTDecodePipe.java
> +	private @Getter String customClaimsParams;
Ik zou verwachten dat ik ook een jwksUrl op zou kunnen geven

2021-04-19 13:17 UTC, ricardovh commented
> Je hebt nu een encode en een decode pipe gemaakt. In dergelijke gevallen hebben we meestal/liever één pipe met een directon- of action- attribuut. Dat beperkt de lijst van Pipes. Heb je dat nu bewust niet gedaan?

Ik was bewust begonnen met 2 pipes, omdat ik bij de start niet wist hoeveel overlap de properties van de pipes zouden hebben en ik denk met de code nagenoeg af dat de overlap nog steeds beperkt is. Een deel van de attributen heeft weliswaar dezelfde naam, maar heeft compleet tegenovergestelde betekenissen (Encode: voeg claim toe aan JWT - Decode: controleer of claim in JWT zit), de rest is niet van toepassing voor de andere richting en vraag ik me af hoe overzichtelijk dat is met auto-complete vanuit de XSD of de Frank!Flow als er allemaal suggesties komen die niet van toepassing zijn. Maar dat is misschien ook een bredere discussie die gevoerd kan worden.

Om het gelijk te trekken met de overige pipes zal ik het nu wel samen voegen tot 1 pipe.

2021-04-22 14:59 UTC, ricardovh commented
See #1737, solution should be in another direction

2021-04-22 14:59 UTC, closed without merging