adapted readme picture
ibissource/iaf pull request #1723
Opened 2021-04-19 08:52 UTC by githubapreinders

Changed IAF to Frank Framework in the Readme picture IAF.png

2021-04-26 10:41 UTC, gvanbrakel requested changes
De aanpassingen die gedaan zijn aan het plaatje (ibis -> frank) zijn goed, maar het plaatje zelf klopt eigenlijk niet. Het suggereert dat een adapter altijd bestaat uit een Listener, dan een of meer Pipes, en dan een Sender. Dat zet je op het verkeerde been over wat een Listener en wat een Sender is in het framework.

2021-05-05 06:54 UTC, gvanbrakel approved these changes

2021-05-10 15:00 UTC, gvanbrakel approved these changes

2021-05-17 08:46 UTC, nielsm5 approved these changes

2021-05-17 08:46 UTC, merged