Remove axis dependency
ibissource/iaf pull request #1750
Opened 2021-04-29 16:12 UTC by alisihab

Closes #1722

2021-04-29 16:30 UTC, gvanbrakel requested changes

2021-04-29 16:30 UTC, gvanbrakel commented on core/src/test/resources/Soap/ignoreElements.xsl
> +	<xsl:template match="*[local-name()='Security']">
Instead of ``*[local-name()='Security']`` you can write ``*:Security``

2021-04-29 16:30 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/soap/SoapWrapper.java
> +//			msg.setMessageContext(msgContext);
Please delete these lines

2021-04-30 06:15 UTC, gvanbrakel approved these changes

2021-04-30 13:41 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
> +						pipelineSession.put("attachment" + i, attachmentPart.getRawContent());
I agree

2021-05-03 08:12 UTC, nielsm5 approved these changes

2021-05-03 08:12 UTC, merged