Frank!Doc uses the attribute prohibited on certain elements
ibissource/iaf pull request #1767
Opened 2021-05-03 11:24 UTC by mhdirkse

2021-05-03 17:09 UTC, gvanbrakel requested changes

2021-05-03 17:09 UTC, gvanbrakel commented on frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/XsdVersion.java
> +		abstract AttributeUse getAttributeRoleNameUse();
Ik zou deze getRoleNameAttributeUse genoemd hebben

2021-05-04 08:09 UTC, mhdirkse commented on frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/XsdVersion.java
> +		abstract AttributeUse getAttributeRoleNameUse();
Gedaan.

2021-05-04 09:11 UTC, nielsm5 commented
Could you remove the @Ignore in the ConfigurationDigesterTest, so we can validate that it works?

2021-05-04 13:18 UTC, nielsm5 approved these changes

2021-05-04 13:37 UTC, gvanbrakel approved these changes

2021-05-04 13:38 UTC, merged