Extend transformerParameter type check with Message
ibissource/iaf pull request #1776
Opened 2021-05-04 16:13 UTC by alisihab

Parameters sent to setTransformerParameters method is from Object type. There could be parameters like Boolean and Integer which cannot be Message at the moment. 
Closes #1690

2021-05-05 06:25 UTC, gvanbrakel approved these changes

2021-05-05 07:37 UTC, nielsm5 requested changes
Could you add a few tests to check for `String`, `Reader`, `InputStream`, `byte[]` and `Message`?

2021-05-11 11:27 UTC, nielsm5 approved these changes

2021-05-14 07:10 UTC, gvanbrakel approved these changes

2021-05-14 07:10 UTC, merged