Fix calculating root validations from message root attributes
ibissource/iaf pull request #1793
Opened 2021-05-10 09:02 UTC by gvanbrakel

2021-05-11 10:32 UTC, nielsm5 requested changes

2021-05-11 10:32 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> +		}
Vind je het niet handiger om gewoon een exceptie te gooien?

2021-05-11 10:32 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
>  		if (responseRoot!=null) {
Dit moet dan StringUtils.isNotEmpty worden

2021-05-11 10:32 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
> -			addResponseRootValidation(Arrays.asList(responseRoot.split(",")));
Kan die split weg?

2021-05-11 10:32 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/soap/WsdlGenerator.java
> +    	return rootSpecification;
Als MessageRoot meerdere waardes kan hebben is de huidige naam niet zo handig

2021-05-12 06:27 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
> -			addResponseRootValidation(Arrays.asList(responseRoot.split(",")));
die is al weg

2021-05-17 08:22 UTC, nielsm5 approved these changes

2021-05-17 08:23 UTC, merged