Format only xml like text in larva comparison
ibissource/iaf pull request #1828
Opened 2021-05-19 10:46 UTC by alisihab

Closes #1790

2021-05-20 08:13 UTC, nielsm5 commented on webapp/src/main/webapp/larva/assets/lib.js
> +		// if it is xml
Since you're fetching `s[i]` 3 times, it might perform better if you assign the value first;
`var j = s[i];`

2021-05-20 11:38 UTC, gvanbrakel requested changes

2021-05-25 16:08 UTC, nielsm5 requested changes

2021-05-25 16:08 UTC, nielsm5 commented on webapp/src/main/webapp/larva/assets/lib.js
> +		var text = $(elementId).value;
Can this be moved to the `jsonFormat` ?

2021-05-26 13:50 UTC, nielsm5 approved these changes

2021-05-27 15:36 UTC, gvanbrakel requested changes

2021-05-27 15:36 UTC, gvanbrakel commented on webapp/src/main/webapp/larva/assets/lib.js
> +		}
When the formatting fails, e.g. due to a syntax error, something like the original text should be displayed.

2021-05-28 08:58 UTC, gvanbrakel approved these changes

2021-05-28 09:13 UTC, merged