Frank!Doc: Elements in types in groups
ibissource/iaf pull request #1846
Opened 2021-05-25 14:33 UTC by mhdirkse

2021-05-26 14:13 UTC, mhdirkse commented
The last commit message says: "not ok yet". This is about an error that happened in Edge or Internet Explorer, not in Chrome. We do not want to support Internet Explorer anymore, so this pull request should be ready.

2021-05-26 15:57 UTC, mhdirkse commented on webapp/src/main/webapp/iaf/frankdoc/js/app.js
> +		var memberNames = [];
This is duplicate code now because we have a function to do this. I am going to fix this.

2021-05-26 16:08 UTC, mhdirkse commented on webapp/src/main/webapp/iaf/frankdoc/js/app.js
> +		var memberNames = [];
Done

2021-05-27 11:11 UTC, gvanbrakel requested changes
Als ik de examples bekijk, dan zie ik een 'Other' in 'groups' en in 'types'.
In 'groups' verwacht ik die, maar niet in 'types'.

2021-05-28 07:48 UTC, mhdirkse commented
Ik denk dat niet alleen group "Other" er moet zijn maar ook type "Other". Ik citeer wat er in type "Other" zit:

            "name":"Other",
            "members":[
                "nl.nn.adapterframework.configuration.Configuration"
            ]

Je ziet hier het FrankElement "Configuration" gedefiniëerd. "Configuration" is het top-niveau element en kan dus niet voorkomen als kind van iets anders. Daarom is er in het model geen ElementType waar "Configuration" een member van is. Ik moest dus een apart type, "Other" introduceren om hem in te passen in de groups, types, elements hiërarchie.

2021-05-28 08:57 UTC, gvanbrakel requested changes
Het type van de groep voor Configuration moet niet 'Other' zijn, maar 'nl.nn.adapterframework.configuration.Configuration'.
Ook kan je, voor groepen die maar één member bevatten, die hetzelfde is als de typenaam, de members weglaten.

2021-05-28 11:08 UTC, mhdirkse commented
Het type "Other" is "nl.nn. ... .Configuration" geworden zoals Gerrit vraagt. Ik heb tegen Gerrit gezegd dat we weinig data besparen door de members weg te laten van types met één member. Gerrit ging er toen mee akkoord dat we het member dan maar gewoon toevoegen.

2021-05-28 12:47 UTC, gvanbrakel approved these changes

2021-05-28 13:05 UTC, nielsm5 approved these changes

2021-05-28 13:09 UTC, merged