Fix determining service location in the generated wsdl
ibissource/iaf pull request #1848
Opened 2021-05-25 16:29 UTC by alisihab

Closes #1798

2021-05-26 13:44 UTC, nielsm5 requested changes

2021-05-26 13:44 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java
> +				}
Routing based on the namespace uri doesn't mean the uri is the external address.
If no address has been provided, the endpoint should be `services/rpcrouter`.
See NamespaceUriProvider and NamespaceUriProviderBean

2021-05-27 07:48 UTC, nielsm5 approved these changes

2021-05-27 15:33 UTC, gvanbrakel approved these changes

2021-05-28 07:30 UTC, merged