Auto detect namedParameters in the query
ibissource/iaf pull request #1875
Opened 2021-06-02 10:50 UTC by alisihab

Closes #1826

2021-06-03 15:47 UTC, gvanbrakel requested changes

2021-06-03 15:47 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
> +		assertEquals("?{param}", result.asString());
Could you remove this assertEquals and move the exception.expect to just before the sendMessage()? 
As it is now it is confusing if you don't read very carefully.

2021-06-03 15:47 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
> +		assertEquals("<result><rowsupdated>1</rowsupdated></result>", result.asString());
Could you remove this assertEquals and move the exception.expect to just before the sendMessage()? 
As it is now it is confusing if you don't read very carefully.

2021-06-03 15:47 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
> +		assertEquals("<result><rowsupdated>1</rowsupdated></result>", result.asString());
Could you remove this assertEquals and move the exception.expect to just before the sendMessage()? 
As it is now it is confusing if you don't read very carefully.

2021-06-03 15:47 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
> +		assertEquals("<result><rowsupdated>1</rowsupdated></result>", result.asString());
Could you remove this assertEquals and move the exception.expect to just before the sendMessage()? 
As it is now it is confusing if you don't read very carefully.

2021-06-04 12:16 UTC, nielsm5 approved these changes

2021-06-04 12:33 UTC, gvanbrakel approved these changes

2021-06-04 12:33 UTC, merged