Fix Iaf test warnings about jmsRealm
ibissource/iaf pull request #1878
Opened 2021-06-03 11:58 UTC by mhdirkse

2021-06-03 14:53 UTC, gvanbrakel requested changes
Je zet nu overal `datasourceName="${jdbc.datasource.default}"`, maar dat is als het goed is de default. Het zou dus ook zonder moeten kunnen. Zou je kunnen checken of dat ook goed gaat?

2021-06-07 10:52 UTC, mhdirkse commented
Ik heb zo veel mogelijk datasourceName properties weggehaald zonder de Larva testen te laten falen. Toen ik ze allemaal weg had faalden er testen. Ik heb toen de datasourceName attributes die ik nodig had teruggezet. Ik heb gecontroleerd dat de Larva tests werken zoals de pull request nu is.

Ik kan de jmsRealm elementen niet weghalen zonder het F!F of de testen stuk te maken. Gerrit, je zei dat dat werk uitgesteld mag worden tot een andere pull request.

2021-06-07 11:03 UTC, nielsm5 approved these changes

2021-06-08 07:48 UTC, mhdirkse commented
Ik heb getest dat ibis4example ook nog werkt. Er zijn geen fouten in het Adapter Status scherm en de Hello Worlds adapter werkt.

2021-06-11 08:25 UTC, gvanbrakel approved these changes

2021-06-11 08:25 UTC, merged