Add unit test for registered property descriptors and fix discrepancies
ibissource/iaf pull request #1886
Opened 2021-06-07 13:53 UTC by alisihab

Closes #1872

2021-06-08 09:09 UTC, gvanbrakel requested changes

2021-06-08 11:39 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/configuration/digester/MapPropertyDescriptorsTest.java
> +						PropertyDescriptor pd = Arrays.stream(pds)
Can't you just do `PropertyUtils.getWriteMethod(pd);` ?

2021-06-08 11:40 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/configuration/digester/MapPropertyDescriptorsTest.java
> +					propertyName = propertyName.substring(0, 1).toLowerCase() + propertyName.substring(1);
Perhaps `PropertyUtils.getPropertyDescriptor(bean, method);` might be easier here?

2021-06-08 12:24 UTC, alisihab commented on core/src/main/java/nl/nn/adapterframework/pipes/CsvParserPipe.java
>  	@IbisDoc({"1", "Specifies if the first line should be treated as header or as data", "true"})
I'll check this in the other PR

2021-06-09 07:09 UTC, alisihab commented on core/src/main/java/nl/nn/adapterframework/pipes/CsvParserPipe.java
>  	@IbisDoc({"1", "Specifies if the first line should be treated as header or as data", "true"})
better to do it here to prevent any conflict

2021-06-09 09:12 UTC, alisihab commented
merged to #1889

2021-06-09 09:12 UTC, closed without merging