Fix 1944 make sure that the sub-directories are created before the file
ibissource/iaf pull request #1952
Opened 2021-06-24 14:06 UTC by alisihab

Fixes #1944

2021-06-25 06:42 UTC, gvanbrakel requested changes

2021-06-25 06:42 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
> +							if (isCreateSubdirectories()) {
Is createSubDirectories only used when keepOriginalFilename=false?
Could you create tests for all combinations of options?

2021-06-29 06:42 UTC, gvanbrakel requested changes

2021-06-29 06:42 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
> +		keepOriginalFilePath = b;
When you replace a setter, like this, then call the new setter from the replaced one, instead of copying the contents

2021-06-29 06:59 UTC, gvanbrakel approved these changes

2021-06-30 12:27 UTC, nielsm5 approved these changes

2021-06-30 12:27 UTC, merged