fix #1959 get session key as string
ibissource/iaf pull request #1960
Opened 2021-06-28 07:24 UTC by alisihab

2021-06-28 09:01 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
> +				if (styleSheetNameToUse != null) {
I think it's safer to do a nullcheck before doing asString.
You can do
```
Message styleSheetNameToUse = session.getMessage(styleSheetNameSessionKey);
if (!Message.isEmpty(styleSheetNameToUse )) { ... }
```

2021-06-28 19:41 UTC, gvanbrakel requested changes

2021-06-28 19:41 UTC, gvanbrakel commented on RELEASES.md
> +- JsonPipe produces json without root element
Please add: the previous  behaviour can be obtained by setting `version="1"`

2021-06-29 06:58 UTC, gvanbrakel approved these changes

2021-06-30 12:27 UTC, merged