Clean up classes
ibissource/iaf pull request #1964
Opened 2021-06-28 16:36 UTC by nielsm5

Change ApplicationContext to ConfigurationContext
Remove `ExceptionUtils` from `IbisExecption`
Remove NPE nightmare: `pipeLine.getAdapter().getConfiguration().getIbisManager()`
Use String Iterator for `Misc#listToString(...)`
Fix and refactor StreamPipeTest

2021-06-28 16:36 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/pipes/StreamPipeTest.java
> -import org.apache.commons.httpclient.methods.multipart.StringPart;
It's all about removing these 'old' commons-httpclient imports

2021-06-28 16:37 UTC, nielsm5 commented on ladybug/src/main/java/nl/nn/ibistesttool/PipeDescriptionProvider.java
> +				return pipeDescription;
We cannot return as the Testtool requires a checkpointName.

2021-06-28 19:38 UTC, gvanbrakel requested changes

2021-06-29 08:06 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/IbisException.java
> +     * </ul>
Done!

2021-06-29 08:09 UTC, gvanbrakel approved these changes

2021-06-29 08:32 UTC, merged