added test mail adapater
ibissource/iaf pull request #1973
Opened 2021-07-01 15:15 UTC by LeroyJenkinss

If added this adapter to see if the mailing service works

2021-07-02 07:46 UTC, gvanbrakel requested changes

2021-07-02 07:46 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/ConfigurationLarva2.xml
> +			</pipe>
Deze pipes worden niet gebruikt, die kan je dus deleten

2021-07-02 07:46 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/ConfigurationLarva2.xml
> +	<adapter name="Larva2" active="${larva.adapter.active}">
Ik zou een naam verwachten als 'test send mail'

2021-07-02 07:46 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/Configuration.xml
> +	<!ENTITY Larva2 SYSTEM "./ConfigurationLarva2.xml">
ik zou een naam verwachten als  ConfigurationTestSendMail

2021-07-02 07:46 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/ConfigurationLarva2.xml
> +	</scheduler>
Deze is ook niet nodig (en verkeerd!)

2021-07-02 09:57 UTC, gvanbrakel approved these changes

2021-07-02 10:03 UTC, nielsm5 requested changes

2021-07-02 10:03 UTC, nielsm5 commented on test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml
> +				<param name="result" sessionKey="result" />
Waar komen deze sessionkeys vandaan? Gaat dit wel goed zo, naar wie moet de mailSender nu een mail sturen?

2021-07-02 10:03 UTC, nielsm5 commented on test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml
> +			</pipe>
Ik denk dat deze pipe uit kan? Als je echt puur de MailSender wilt testen hoef je hem niet zo te stubben toch?

2021-07-06 11:13 UTC, nielsm5 commented on test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml
> +				active="${larva.adapter.mail.active}"
Ik denk dat deze active weg moet, anders bomb't de CreateMail dat hij geen forward kan vinden

2021-07-07 08:27 UTC, nielsm5 commented on test/src/main/configurations/MainConfig/ConfigurationReceivers.xml
> -				maxRetries="1"
Deze hoeven toch niet weg?

2021-07-07 08:28 UTC, nielsm5 commented on test/src/main/configurations/UTIL/ConfigurationLarva.xml
> -				active="${larva.adapter.mail.active}"
En deze mag ook blijven, die staat in de kit ergens dacht ik

2021-07-07 08:28 UTC, nielsm5 commented on test/src/main/resources/DeploymentSpecifics.properties
> +testsendmail.adapter.active
dan wel graag standaard uit :)

2021-07-07 08:29 UTC, nielsm5 commented on test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml
> +				active="${larva.adapter.mail.active}"
Maar deze moet nog steeds weg!

2021-07-08 07:25 UTC, LeroyJenkinss commented on test/src/main/configurations/MainConfig/ConfigurationReceivers.xml
> -				maxRetries="1"
default is toch 1

2021-07-08 11:57 UTC, nielsm5 commented on core/src/main/resources/AppConstants.properties
> +warnings.suppress.sqlInjections=true
niet in de appconstants gek, dan is het voor alle ibissen overal altijd
In de deploymentspecifics van iaf-test :)

2021-07-12 08:15 UTC, nielsm5 approved these changes

2021-07-12 09:42 UTC, gvanbrakel approved these changes

2021-07-12 09:42 UTC, merged