Fix #1959 Get message from session
ibissource/iaf pull request #1989
Opened 2021-07-06 13:22 UTC by alisihab

2021-07-12 09:39 UTC, nielsm5 commented on cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java
> +			throw new SenderException("Unable to get filename from pipeline session");
This is not entirely correct, `fileName` may be empty. Perhaps you could do a `if(Message.isNotEmpty(...` first before trying to parse a potential `null` as String

2021-07-12 09:41 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/extensions/rekenbox/Adios2XmlPipe.java
> +				throw new PipeRunException(this, "unable to get rekenbox session key from pipeline session", e);
I think the error should use the attribute name as a whole `rekenboxSessionKey`

2021-07-13 09:18 UTC, nielsm5 approved these changes

2021-07-14 07:39 UTC, gvanbrakel requested changes

2021-07-14 07:39 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
> +						blobSessionVar=session.getMessage(getBlobSessionKey()).asString();
This is not always a String. It is used in JdbcUtil.streamBlob()

2021-07-14 07:39 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
> +						clobSessionVar=session.getMessage(getClobSessionKey()).asString();
This is not always a String. It is used in JdbcUtil.streamClob()

2021-07-15 09:38 UTC, gvanbrakel approved these changes

2021-07-15 09:38 UTC, merged