Replace stub4testtool.xsl with filters
ibissource/iaf pull request #1996
Opened 2021-07-07 12:59 UTC by ricardovh

2021-07-07 13:01 UTC, ricardovh commented
Note to self: AttributesWrapper needs to be reworked, does not completely process the removal of attributes (indices are not updated)

2021-07-12 09:19 UTC, ricardovh commented
Builds on #1981

2021-07-12 13:01 UTC, nielsm5 requested changes

2021-07-15 09:36 UTC, gvanbrakel requested changes

2021-07-15 09:36 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/filters/Stub4TesttoolFilter.java
> +			Stub4TesttoolFilter filter = new Stub4TesttoolFilter(tp.getTransformerHandler(), resolver);
Hier kan/moet je tp.getTransformerFilter() gebruiken.
Stub4TesttoolFilter hoeft dan geen eigen class te zijn; getStub4TesttoolContentHandler kan een method in ConfigurationUtils worden

2021-07-19 11:51 UTC, gvanbrakel requested changes

2021-07-19 11:51 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationUtilsTest.java
> +		parameters.put(ConfigurationUtils.STUB4TESTTOOL_XSLT_VALIDATORS_PARAM, disableValidators);
In een unit test moet je niet de constanten uit de class under test gebruiken, maar in de test class gedefinieerde constanten. Daarmee zorg je er voor dat als iemand per ongeluk de waarde van deze constanten verandert, dat dat opgemerkt wordt doordat de test faalt.

2021-07-19 14:39 UTC, gvanbrakel approved these changes

2021-07-23 11:16 UTC, nielsm5 approved these changes

2021-07-23 11:16 UTC, merged