add FileSystem adapter to core/IAF-Util
ibissource/iaf pull request #2002
Opened 2021-07-08 06:58 UTC by Bibi0803

And add FileSystem view as a menu item to Frank console

2021-07-30 07:10 UTC, gvanbrakel requested changes

2021-07-30 07:10 UTC, gvanbrakel commented on core/src/main/resources/IAF_Util/ConfigurationFileSystem.xml
> +		<pipeline firstPipe="switchCleanFilesystem">
It is not necessary to set the firstPipe attribute, if it refers to the first pipe of the pipeline

2021-07-30 07:10 UTC, gvanbrakel commented on core/src/main/resources/IAF_Util/ConfigurationFileSystem.xml
> +		<pipeline firstPipe="isZipfile">
It is not necessary to set the firstPipe attribute, if it refers to the first pipe of the pipeline

2021-07-30 10:18 UTC, gvanbrakel approved these changes

2022-07-04 11:57 UTC, jjansenvr commented
Backend is available in the framework.  webcontent should be added in a config jar.

2022-07-04 11:57 UTC, closed without merging