added extra condition to gettibcoqueues
ibissource/iaf pull request #2007
Opened 2021-07-08 13:58 UTC by githubapreinders

When the list of queues is browsed tibco returns queuenames and a principal; when the principal is empty an exception is given back. At this point the whole queues-summary cannot be displayed. This is the error:

java.util.concurrent.ExecutionException: nl.nn.adapterframework.core.PipeRunException: Pipe [getTibcoQueues] msgId [0ace000c-3a81a2_17a1ea5a2c1_-7d92] exception on showing Tibco queues, url [tcp://DEVP2PLARGEDC1:37222,tcp://DEVP2PLARGEDC2:37222|tcp://DEVP2PLARGEDC1.insim.biz:37243,tcp://DEVP2PLARGEDC2.insim.biz:37243]: (TibjmsAdminInvalidNameException) Error retrieving user, invalid name

After setting logmessages in an overridden GetTibcoQueues.java the empty principal was given back as an empty string (and not as null)

The adapted code works and ignores a queue that has no recognizable principalname. These queues will not be displayed on the summary pages. It seems that on the tibco side of things, an empty principal can be given back as a very rare exception. This has not happened on ACC and PRD environments but would block the GetTibcoQueues service.

Please review and give feedback.

2021-07-08 14:27 UTC, nielsm5 commented on tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
> +				continue;}
Ik denk dat je beter een check kan doen als `if(StringUtils.isEmpty(principal)) { continue; }` dat leest wat makkelijker.

2021-07-09 09:14 UTC, githubapreinders commented on tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
> +				continue;}
Ik heb er if(StringUtils.isNotEmpty(principal)) { continue; } van gemaakt. Dat scheelt een extra conditie.

2021-07-26 06:30 UTC, gvanbrakel requested changes

2021-07-26 06:30 UTC, gvanbrakel commented on tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
> +			log.debug("Caught exception retrieving description for principal [" + principal + "]: " + e.getMessage());
hier graag `, e` i.p.v. ` + e.getMessage()`

2021-07-26 06:30 UTC, gvanbrakel commented on tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
> +			log.debug("Caught URISyntaxException while resolving url [" + url + "]: " + e.getMessage());
hier graag `, e` i.p.v. ` + e.getMessage()`

2021-07-26 06:30 UTC, gvanbrakel commented on tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
> +			log.debug("Caught UnknownHostException while resolving url [" + url + "]: " + e.getMessage());
hier graag `, e` i.p.v. ` + e.getMessage()`

2021-07-26 08:19 UTC, gvanbrakel approved these changes

2021-07-26 10:15 UTC, merged