Remove Guava
ibissource/iaf pull request #2017
Opened 2021-07-12 13:57 UTC by nielsm5

2021-07-12 14:48 UTC, gvanbrakel approved these changes

2021-07-12 14:49 UTC, gvanbrakel requested changes

2021-07-13 07:49 UTC, nielsm5 commented on aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionResult.java
> +	private void buildXmlFromResult(XmlBuilder main, CisConversionResult cisConversionResult, boolean isRoot) {
Is een recursief ding.. Elk attachment is ook een CisConversionResult

2021-07-13 13:29 UTC, gvanbrakel approved these changes

2021-07-13 13:30 UTC, merged