Fix #1751 Add option to use ServerFileName as the filename to FxfWrapperPipe
ibissource/iaf pull request #2018
Opened 2021-07-12 14:08 UTC by alisihab

Closes #1751

2021-07-14 06:32 UTC, gvanbrakel requested changes

2021-07-14 06:32 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java
> +				"<ns0:ClientFilename>/filename.xml.zip</ns0:ClientFilename>\n" +
Could you also test without an initial slash?

2021-07-14 06:32 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java
> +			String xpathFilename = isUseServerFilename() ? "/OnCompletedTransferNotify_Action/ServerFilename" : "/OnCompletedTransferNotify_Action/ClientFilename";
Could you make constants for the fixed string values?

2021-07-14 14:51 UTC, gvanbrakel approved these changes

2021-07-15 11:49 UTC, nielsm5 approved these changes

2021-07-15 11:49 UTC, merged