Test mail adpater
ibissource/iaf pull request #2020
Opened 2021-07-13 07:59 UTC by LeroyJenkinss

changing sender mail

2021-07-14 06:28 UTC, gvanbrakel requested changes

2021-07-14 06:28 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/Larva/xsl/CreateMail.xsl
> +	<xsl:param name="hostname">asdf435sdf</xsl:param>
Hier een herkenbare naam gebruiken, zoals `fakehostname` of `host.under.test`.
Dat bespaart je uitleg zoals:
```
[Gisteren 09:52] Ualit, T. (Tarik)
asdf435sdf is de servernaam
```

2021-07-14 06:28 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/Larva/xsl/CreateMail.xsl
> +			<from><xsl:value-of select="$from"/> &lt;devopshelpdesk@wearefrank.nl&gt;</from>
Met deze testadapter kan ju nu alleen maar mail naar `devopshelpdesk@wearefrank.nl` sturen. Dat beperkt de bruikbaarheid.

2021-07-14 06:28 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml
> +				<param name="mailaddresses" value="${errorreport.mailaddresses.fail}" />
Als je hier de mail adressen uit het input bericht haalt kan je beter/makkelijker testen wat er wel en niet werkt.

2021-07-14 09:01 UTC, nielsm5 commented
Waarom is er behoefte voor een 3e mail adapter?

2021-11-12 16:36 UTC, nielsm5 commented
Deze is ondertussen (in delen) al gemerged toch?

2021-11-12 16:36 UTC, closed without merging