Fix warnign "WsdlXmlValidator [ndn] attribute [schemaLocation] for wsdl [/WsdlXmlValidator/NoDefaultNamespace/NoDefaultNamespace.wsdl] should only be set when addNamespaceToSchema=true"
ibissource/iaf pull request #2025
Opened 2021-07-15 10:13 UTC by Bibi0803

2021-07-15 11:12 UTC, gvanbrakel requested changes

2021-07-15 11:12 UTC, gvanbrakel commented on test/src/main/configurations/MainConfig/ConfigurationWsdlXmlValidator.xml
> +				wsdl="/WsdlXmlValidator/NoDefaultNamespace/NoDefaultNamespace.wsdl">
The original configuration also tests that the operation does not break when the schemaLocation has been set, so if you remove that here, that test is lost.
If you still want to get rid of the warning here, you should extend the unit test you created to see that a pipe confgured as the original works as expected

2021-07-19 11:43 UTC, gvanbrakel approved these changes

2021-07-23 07:56 UTC, nielsm5 approved these changes

2021-07-23 07:56 UTC, merged