added devops mailaddress so mails can be forwarded
ibissource/iaf pull request #2043
Opened 2021-07-20 11:14 UTC by LeroyJenkinss

2021-07-20 14:38 UTC, gvanbrakel requested changes

2021-07-20 14:38 UTC, gvanbrakel commented on test/src/main/configurations/UTIL/Larva/xsl/CreateMail.xsl
> +	<xsl:variable name="from" select="$sender"/>
Kan het ook met `<xsl:variable name="from" select="concat($hostname, ' &lt;', $sender, '&gt;')"/>`?

2021-07-26 10:04 UTC, gvanbrakel approved these changes

2021-07-26 11:41 UTC, nielsm5 approved these changes

2021-07-26 11:44 UTC, merged