Fix scanningDirectoryClassLoader shutdown not removing running threads
ibissource/iaf pull request #2053
Opened 2021-07-22 14:32 UTC by nielsm5

2021-07-22 15:26 UTC, gvanbrakel requested changes

2021-07-22 15:26 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java
> +			Resource xsdResource = Resource.getResource(xsdFile.getPath());
Zou niet xsdFile zelf ook een resource kunnen/moeten zijn?

2021-07-22 15:26 UTC, gvanbrakel commented on ibm/src/main/java/nl/nn/adapterframework/util/IbmMisc.java
> +    public static String getConfigurationResourcePath() throws IOException {
Kan je dit zomaar aanpassen? Wordt het ergens gebruikt?

2021-07-22 15:26 UTC, gvanbrakel commented on ibm/src/main/java/nl/nn/adapterframework/util/IbmMisc.java
> +    public static String getConfigurationServerPath() throws IOException {
Kan je dit zomaar aanpassen? Wordt het ergens gebruikt?

2021-07-22 15:55 UTC, nielsm5 commented on ibm/src/main/java/nl/nn/adapterframework/util/IbmMisc.java
> +    public static String getConfigurationResourcePath() throws IOException {
Nope nergens. Ik vond het eigenlijk ook zonde om het zomaar weg te gooien ..

2021-07-22 15:55 UTC, nielsm5 commented on ibm/src/main/java/nl/nn/adapterframework/util/IbmMisc.java
> +    public static String getConfigurationServerPath() throws IOException {
Nope nergens. Ik vond het eigenlijk ook zonde om het zomaar weg te gooien ..

2021-07-23 10:04 UTC, gvanbrakel approved these changes

2021-07-23 10:10 UTC, merged