Fix outputwrapper not being aop'd
ibissource/iaf pull request #2111
Opened 2021-08-12 11:54 UTC by nielsm5

2021-08-15 06:14 UTC, gvanbrakel requested changes

2021-08-15 06:14 UTC, gvanbrakel commented on ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
> +	public PipeRunResult debugValidatorInputOutputAbort(ProceedingJoinPoint proceedingJoinPoint, PipeLine pipeLine, IValidator validator, Message message, PipeLineSession pipeLineSession, String message
Als je deze method maakt, met het argument messageRoot, dan zou je die messageRoot ook moeten laten zien.
Anders kan  je net zo goed `debugPipeInputOutputAbort` gebruiken.

2021-08-15 06:14 UTC, gvanbrakel commented on ladybug/src/main/resources/springIbisDebuggerAdvice.xml
> +				arg-names="message, session, next"
goed dat je dit gevonden hebt.
We moeten echt af van dat ge-AOP waar het ook programmatisch kan!

2021-08-15 08:12 UTC, nielsm5 commented on ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
> +	public PipeRunResult debugValidatorInputOutputAbort(ProceedingJoinPoint proceedingJoinPoint, PipeLine pipeLine, IValidator validator, Message message, PipeLineSession pipeLineSession, String message
Heb je enige suggestie waar ik de messageRoot kwijt kan? Misschien als `-> responseRoot` oid?

2021-08-15 08:24 UTC, gvanbrakel commented on ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
> +	public PipeRunResult debugValidatorInputOutputAbort(ProceedingJoinPoint proceedingJoinPoint, PipeLine pipeLine, IValidator validator, Message message, PipeLineSession pipeLineSession, String message
je kan `Debugger.showValue()` gebruiken

2021-08-16 08:06 UTC, gvanbrakel requested changes

2021-08-16 08:06 UTC, gvanbrakel commented on ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
> +			ibisDebugger.showValue(messageId, "ResponseRoot", messageRoot);
Het is een beetje 'jumping into conclusions'  om hier het label 'responseRoot' aan mee te geven. Er kan zomaar een situatie ontstaan dat het ook voor requests gebruikt gaat worden. Iets als 'Mandatory Message Root' lijkt me beter.

2021-08-16 08:50 UTC, gvanbrakel approved these changes

2021-08-16 08:52 UTC, merged