Refactor MessageKeeper messages to event based messages
ibissource/iaf pull request #2140
Opened 2021-08-20 12:12 UTC by nielsm5

2021-08-20 12:43 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java
> +//			ibisContext.log(configuration.getName(), null, message);
Will conflict with #2130

2021-08-30 09:31 UTC, gvanbrakel requested changes

2021-08-30 09:31 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java
> +		configuration.publishEvent(new ConfigurationMessageEvent(configuration, message));
Kan je hiervoor een configuration.log(message) maken?
Die kan dan publishEvent(new ConfigurationMessageEvent(this, message) doen

2021-08-30 15:54 UTC, gvanbrakel approved these changes

2021-08-30 15:55 UTC, merged