Do not duplicate the stack trace in the log file
ibissource/iaf pull request #2163
Opened 2021-08-30 12:32 UTC by alisihab

Closes #2142

2021-08-30 16:04 UTC, gvanbrakel reviewed
Does this have no impact on iaf-test?

2021-08-30 16:31 UTC, alisihab commented
> Does this have no impact on iaf-test?

ran the scenarios, none of them requires adjusting. This may not be the expected solution. You may see the the difference that came with the change in the attached files.
[before.txt](https://github.com/ibissource/iaf/files/7078119/before.txt)
[after.txt](https://github.com/ibissource/iaf/files/7078120/after.txt)

2021-09-10 14:08 UTC, gvanbrakel reviewed
The javadoc of 'org.apache.logging.log4j.core.impl.ThrowableProxy' says: "Wraps a Throwable to add packaging information about each stack trace element." It also has a 'commonElementCount'. Doesn't this class do all that is necessary?

2021-09-14 07:34 UTC, nielsm5 requested changes

2021-09-15 12:51 UTC, gvanbrakel approved these changes

2021-09-16 08:03 UTC, nielsm5 approved these changes

2021-09-16 08:04 UTC, merged