Frank!Doc: Test conflicting candidates for default of generic element option
ibissource/iaf pull request #2165
Opened 2021-08-30 14:34 UTC by mhdirkse

The functionality was there already. We only have to test it.

2021-08-30 14:36 UTC, mhdirkse commented
Here are the warnings that are produced for the added test:

```
16:29:17,607 WARN  ConfigChildSet.getGenericElementOptionDefault():168[] ConfigChildSet [ConfigChildSet(ObjectConfigChild(MyElement.registerB(IChild1)), ObjectConfigChild(MyElement.registerB(IChild2)))] has multiple candidates for the default element: [nl.nn.adapterframework.frankdoc.testtarget.plural.config.defaultClassname.Child1, nl.nn.adapterframework.frankdoc.testtarget.plural.config.defaultClassname.Child2]
16:29:17,611 WARN  ConfigChildSet.getGenericElementOptionDefault():168[] ConfigChildSet [ConfigChildSet(ObjectConfigChild(Master.registerA(IInterface1)), ObjectConfigChild(Master.registerA(IInterface2)))] has multiple candidates for the default element: [nl.nn.adapterframework.frankdoc.testtarget.plural.config.defaultClassname.Interface1, nl.nn.adapterframework.frankdoc.testtarget.plural.config.defaultClassname.Interface2]

```

2021-08-30 15:41 UTC, nielsm5 requested changes
Je test het gooien van de warning niet, is dat mogelijk met de log4j TestAppender ?

2021-08-30 16:34 UTC, mhdirkse commented
We testen nergens anders de logging die de Frank!Doc maakt. Als we dit willen, moeten we dan een aparte log4j configuratie maken?

Misschien kan ik een comment bij de test zetten om te waarschuwen dat we niet testen dat het log statement eruit komt? Met deze PR dacht ik: iets is beter dan niets.

2021-08-31 08:17 UTC, mhdirkse commented
I am resolving a conflict. I will make this ready-for-review when done.

2021-08-31 13:11 UTC, nielsm5 approved these changes

2021-09-03 07:05 UTC, gvanbrakel approved these changes

2021-09-03 07:05 UTC, merged