Frank!Doc: Parameters
ibissource/iaf pull request #2169
Opened 2021-08-31 11:13 UTC by mhdirkse

2021-08-31 12:06 UTC, gvanbrakel approved these changes

2021-09-13 09:54 UTC, nielsm5 requested changes

2021-09-13 09:54 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/frankdoc/js/controllers.js
> +				}
Je kan ook `ng-if="element.parameters || element.parameterDescription"` gebruiken. Dat scheelt code en verbetert de leesbaarheid.

2021-09-13 11:31 UTC, mhdirkse commented on frankDoc/src/test/resources/doc/examplesExpected/parameters.json
> +            "specificParameters":[
Gedaan

2021-09-13 11:31 UTC, mhdirkse commented on frankDoc/src/test/resources/doc/examplesExpected/parameters.json
> +            "parametersMeaning":"This is the meaning of the parameters of Master"
Gedaan

2021-09-13 11:32 UTC, mhdirkse commented on webapp/src/main/webapp/iaf/frankdoc/js/controllers.js
> +				}
Gedaan

2021-09-14 08:16 UTC, nielsm5 approved these changes

2021-09-14 08:17 UTC, merged