Introduce special stop condition forwards to IteratingPipe
ibissource/iaf pull request #2190
Opened 2021-09-09 11:18 UTC by alisihab

Closes #2184

2021-09-09 14:12 UTC, gvanbrakel requested changes

2021-09-13 12:02 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
> +	protected final String STOP_CONDITION_HELD_FORWARD = "stopConditionHeld";
Held is de verleden tijd van iets houden. Halted is stoppen.
Misschien iets van aborted/halted/interrupted gebruiken. Ik denk niet dat 'conditionXXX' er in hoeft.

2021-09-14 14:54 UTC, nielsm5 approved these changes

2021-09-16 06:49 UTC, gvanbrakel requested changes

2021-09-16 06:49 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/StringIteratorPipe.java
> +							return PipeForward.SUCCESS_FORWARD_NAME;
I think finalizeBlock should return the stopReason, and handleItem should return that here.
It would be good to create a test that hits this code.

2021-09-17 13:12 UTC, gvanbrakel requested changes

2021-09-17 13:12 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java
>  		private boolean stopRequested;
I think the variable stopRequested can be fully replaced by stopReason

2021-09-17 13:12 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
> +	protected static final String STOP_CONDITION_MET_FORWARD = "stopConditionMet";
I suggest to use a field in StopReason-enum instead of these constants

2021-09-17 13:12 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
> +		 * @return null when looping should continue, forward name when stop is required.
`return a non null StopReason when stop is required`

2021-09-17 13:12 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
> +		}
This is calculated each time the pipe executes. It is better to calculate it once in configure() and store it in a boolean variable

2021-09-17 13:12 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/StringIteratorPipe.java
> +							return stopReason;
I would expect that the stopReason returned would have been the result of `finalizeBlock()`

2021-09-17 14:20 UTC, gvanbrakel approved these changes

2021-09-18 16:08 UTC, nielsm5 approved these changes

2021-09-18 16:08 UTC, merged