The LICENSE file has a different copyright text, exclude from checking
ibissource/iaf pull request #2244
Opened 2021-09-23 16:07 UTC by mhdirkse

2021-09-23 16:08 UTC, mhdirkse commented
I cannot build the master anymore. This fixes the issue for me

2021-09-23 16:09 UTC, nielsm5 commented
License is already included in the file, perhaps you could remove the slash in front of the text instead.

2021-09-23 16:28 UTC, nielsm5 requested changes
License is already included in the file, perhaps you could remove the slash in front of the text instead.

2021-09-24 07:57 UTC, nielsm5 approved these changes

2021-09-24 09:40 UTC, gvanbrakel commented on pom.xml
> +					<exists>copyrightTemplateFile.txt</exists>
Toch een beetje raar om aan de hand van deze file te bepalen of het de root folder is.

2021-09-24 09:41 UTC, gvanbrakel approved these changes

2021-09-24 10:41 UTC, merged