Add MFH Adapter to iaf-test
ibissource/iaf pull request #2303
Opened 2021-10-06 14:56 UTC by alisihab

2021-11-01 15:43 UTC, gvanbrakel requested changes

2021-11-01 15:43 UTC, gvanbrakel commented on test/src/main/configurations/FileHandling/Configuration_MFH.xml
> +				<Param name="FlowId" value="${mfh.flow1.flowid}" /> <!-- Can be hardcoded or retrieved from the filename depending on the new design-->
If one of the two is there only to support legacy-fxf, then that one should have the long name, e.g. FxfFlowId, and the new one should be called FlowId
Could you also provide a confguration without the legacy?

2021-11-02 15:05 UTC, gvanbrakel requested changes

2021-11-02 15:05 UTC, gvanbrakel commented on test/src/main/configurations/FileHandling/DeploymentSpecifics.properties
> +mfh.flow1.flowid=NNX12345
Could you please rename this one to mfh.flow1.legacyflowid, too?

2021-11-08 14:48 UTC, gvanbrakel approved these changes

2021-11-10 13:13 UTC, nielsm5 approved these changes

2021-11-10 13:13 UTC, nielsm5 commented on test/src/test/testtool/ManagedFileHandler/scenario01.properties
> +step2.dir.init.write					= common/dummy.txt
you can also use `writeLine` that way you don't have to create a new (empty) file

2021-11-10 13:13 UTC, nielsm5 commented on test/src/main/configurations/FileHandling/MFH/xsl/createTriggerMessage.xsl
> +	<xsl:param name="originalFilename"/>
originalFilename doesn't start with a capital o but the other params do!

2021-11-10 14:55 UTC, merged