Upgrade jackson to version 2.13
ibissource/iaf pull request #2421
Opened 2021-11-09 12:00 UTC by alisihab

Closes #2412

2021-11-09 12:45 UTC, nielsm5 requested changes
Have you tested the API?

2021-11-09 13:45 UTC, nielsm5 commented
Don't forget to update the JsonProvider in FrankFrameworkApiContext

2021-11-10 11:06 UTC, nielsm5 approved these changes

2021-11-10 11:08 UTC, nielsm5 commented
I just did a search-in-project for com.fasterxml there are 4 hits in core/tests

2021-11-10 14:44 UTC, nielsm5 approved these changes

2021-11-10 14:55 UTC, gvanbrakel approved these changes

2021-11-10 14:55 UTC, merged