Add ability to upload a file to liquibase script generator
ibissource/iaf pull request #2434
Opened 2021-11-11 07:49 UTC by alisihab

Closes #1484

2021-11-18 08:52 UTC, nielsm5 requested changes

2021-11-18 08:52 UTC, nielsm5 commented on webapp/src/main/webapp/iaf/gui/js/controllers.js
> -	$scope.addLocalAlert = function(type, message) {
I think a merge went wrong here..

2021-11-19 10:36 UTC, nielsm5 requested changes

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +	}
Are you purposely overriding these? If so, please give a brief explanation as to why. Else please remove these methods, as I can imagine it's handy to know which file/changeset contains an error.

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +	}
I can imagine when you delegate everything to log4j you either want to let log4j handle this (and set the loglevel default to INFO, as per the old log4j4ibis.xml).

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +		}
You don't need these if statements, it's the first thing log4j does :)

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +	}
Give a brief explanation that calling this wont do much as the loggers name has already been defined upon creating the logger

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +	}
I think these should also be logged?

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java
> +		LogFactory.setInstance(new LogFactory() {
Please override getLog(String) instead to be able to fetch the correct logger.

2021-11-19 10:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +	private static final Logger log = LogUtil.getLogger(LiquibaseLogger.class);
Please give each logger a name.
Right now all log statements come from the migration.LiquibaseLogger package, which hides it's origin.
You can set the final field in a constructor where you may pass the name of the logger.

2021-11-24 11:28 UTC, nielsm5 approved these changes

2021-11-25 11:09 UTC, gvanbrakel approved these changes

2021-11-25 11:10 UTC, merged