Override liquibase logger with log4j
ibissource/iaf pull request #2463
Opened 2021-11-19 13:41 UTC by alisihab

Closes #2447

2021-11-22 08:46 UTC, nielsm5 submitted a review, later dismissed

2021-11-23 07:41 UTC, gvanbrakel requested changes

2021-11-23 07:41 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseLogger.java
> +		}
I would suggest then to call log.trace()

2021-11-23 13:19 UTC, nielsm5 commented
Please replace with 
```
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-liquibase</artifactId>
			<version>2.14.1</version>
		</dependency>
```

2021-12-06 10:04 UTC, closed without merging