Update JavaDocs about some listeners
ibissource/iaf pull request #2525
Opened 2021-12-10 12:07 UTC by mhdirkse

2021-12-15 08:27 UTC, gvanbrakel requested changes

2021-12-15 08:27 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * bypasses any listeners.
Deze tekst niet opnemen

2021-12-15 08:27 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * Use this listener to receive messages from other adapters or as a dummy listener.
Hier niet 'dummy listener' noemen

2021-12-16 08:05 UTC, mhdirkse commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * bypasses any listeners.
Tekst is weg.

2021-12-16 08:05 UTC, mhdirkse commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * Use this listener to receive messages from other adapters or as a dummy listener.
Gedaan.

2021-12-17 07:52 UTC, gvanbrakel approved these changes

2021-12-17 10:51 UTC, nielsm5 requested changes

2021-12-17 10:51 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * Use this listener to receive messages from other adapters.
```suggestion
 * Use this listener to receive messages from other adapters within the Frank! Application or from other components residing in the same JVM.
 * JavaListeners can receive calls made via de ibis-servicedispatcher, which should be located on the JVM classpath to receive calls from other components in the JVM. If you want to call an adapter in the same Frank! Application, consider using the IbisLocalSender.
```

2021-12-17 10:51 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> + * access a JavaListener, see also our GitHub project ibis-servicedispatcher.
```suggestion
 * The JavaListener listens to Java method calls. You can issue Java method calls using a {@link nl.nn.adapterframework.senders.IbisJavaSender} (external call)
 * or {@link nl.nn.adapterframework.senders.IbisLocalSender} (internal call). 
 * For more information see the ibis-servicedispatcher project.
```

2021-12-17 11:48 UTC, nielsm5 approved these changes

2021-12-17 12:17 UTC, merged