Add unit tests to CompressPipe
ibissource/iaf pull request #2603
Opened 2022-01-07 08:46 UTC by alisihab

2022-01-07 09:11 UTC, nielsm5 approved these changes

2022-01-10 07:34 UTC, gvanbrakel requested changes

2022-01-10 07:34 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
> +				if ("gz".equals(fileFormat) || fileFormat == null && resultIsContent) {
Could you please turn fileFormat into an enum?

2022-01-10 08:47 UTC, nielsm5 approved these changes

2022-01-10 08:51 UTC, gvanbrakel requested changes

2022-01-10 08:51 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
> +		fileFormat = format;
Please also document the FileFormat enum values, and remove the corresponding documentation from the  setter-IbisDoc

2022-01-10 13:24 UTC, gvanbrakel approved these changes

2022-01-10 13:24 UTC, merged

2023-07-12 12:47 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
> -					in.close();
https://github.com/ibissource/iaf/issues/5104