Fix NPE in HelloWorlds when using ApiListener
ibissource/iaf pull request #2612
Opened 2022-01-10 15:33 UTC by jacodg

2022-01-10 17:52 UTC, gvanbrakel commented on example/src/main/resources/ConfigurationHelloWorld.xml
> +			<!-- This listener is used when the API is called as specified in OpenAPI 3.0 at the Webservices page) -->
Hier is een dangling haakje

2022-01-10 17:52 UTC, gvanbrakel commented on example/src/main/resources/ConfigurationHelloWorlds.xml
> +				emptyInputReplacement="- line 1 -&#10;- line 2 -&#10;- line 3 -&#10;- line4 -"
Het lijkt me niet een heel fijn voorbeeld om uit te leggen

2022-01-11 08:53 UTC, jacodg commented on example/src/main/resources/ConfigurationHelloWorld.xml
> +			<!-- This listener is used when the API is called as specified in OpenAPI 3.0 at the Webservices page) -->
Fixed

2022-01-11 11:48 UTC, jacodg commented on example/src/main/resources/ConfigurationHelloWorlds.xml
> +				emptyInputReplacement="- line 1 -&#10;- line 2 -&#10;- line 3 -&#10;- line4 -"
Ik heb nog wat beter naar de HelloWorlds gekeken en deze verbeterd

2022-01-12 13:17 UTC, nielsm5 requested changes
Waar zat de originele NPE? Kan je de stacktrace toevoegen? Ik zie liever een ServiceNotFoundException (oid) dan een NPE...

2022-01-17 18:09 UTC, jacodg commented
Zie hieronder de stacktrace. Je krijgt dit als je iaf-example opstart en dan http://localhost/api/hello-worlds/ aanroept. Er gaat dan null de pipeline in. De eerste pipe (XmlWellFormedChecker) heeft geen probleem met een null message. De tweede pipe (Text2XmlPipe) kan er niet tegen en geeft een NPE. N.a.v. het onderzoeken van deze NPE en comment van Gerrit heb wat verder naar de HelloWorlds gekeken en deze aangepast. Uiteindelijk niet (alleen) om de NPE te vermijden maar om hem uberhaupt duidelijker/beter te maken. Dus graag wel deze PR goedkeuren. :)

```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.FilterReader.<init>(FilterReader.java:55)
	at nl.nn.adapterframework.util.EncapsulatingReader.<init>(EncapsulatingReader.java:39)
	at nl.nn.adapterframework.pipes.Text2XmlPipe.doPipe(Text2XmlPipe.java:64)
	at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:33)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:38)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:62)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:59)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:59)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:67)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$7be8ff2c.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:89)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:183)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$c8900de7.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:38)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:77)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:233)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodI [...]

2022-01-21 10:58 UTC, gvanbrakel requested changes

2022-01-21 10:58 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/Text2XmlPipe.java
> +			try (Writer writer = target.asWriter()) {
Considering that the pipe produces XML, it would be more appropriate to send the output to `target.asContentHandler()` instead of `target.asWriter()`

2022-01-21 10:58 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/Text2XmlPipe.java
> +		} catch(Exception e) {
Just before this catch you must return `target.getPipeRunResult();`

2022-01-21 10:58 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/Text2XmlPipe.java
> +						result = writer.toString();
do not set the result here, it is already streamed to the writer

2022-01-21 10:58 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/Text2XmlPipe.java
> +		return builder.toString();
You can avoid this code by writing to a ContentHandler

2022-01-21 16:20 UTC, alisihab commented on core/src/main/java/nl/nn/adapterframework/pipes/Text2XmlPipe.java
> +	@Deprecated
Yes, it is no more optional to have the declaration. There will be no xml declaration. What do we do for such cases? Remove the attribute completely?

2022-01-24 09:53 UTC, nielsm5 approved these changes

2022-01-24 12:00 UTC, gvanbrakel approved these changes

2022-01-24 12:00 UTC, merged