More mandatory elements and attributes
ibissource/iaf pull request #2650
Opened 2022-01-19 11:07 UTC by gvanbrakel

2022-01-20 14:07 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java
> +	private @Getter String charset=StreamUtil.DEFAULT_INPUT_STREAM_ENCODING;
Deze zou ook gewoon null mogen zijn toch?

2022-01-20 14:12 UTC, nielsm5 requested changes

2022-01-20 14:12 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> +		@EnumLabel("error") ERROR;
Hoeft geen DocumentedEnum te zijn toch? Ik snap dat pipeLineResult dan aangepast moet worden, misschien een todo/taakje voor maken om dit in een losse pr te doen?

2022-01-21 15:36 UTC, nielsm5 approved these changes

2022-01-21 15:36 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> -	public void setCommitOnState(String string) {
kan dit zomaar weg?

2022-01-21 15:47 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> -	public void setCommitOnState(String string) {
Ja, je gaat daar echt nooit iets anders invullen dan 'success'

2022-01-21 15:48 UTC, merged