Always wrap TransactionalDbmsSupportAwareDataSourceProxy
ibissource/iaf pull request #2661
Opened 2022-01-21 13:17 UTC by nielsm5

2022-01-21 14:25 UTC, gvanbrakel requested changes

2022-01-21 14:25 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java
> +			case NARAYANA:
Als je dit doet gebruik je geen Narayana, maar de Spring DataSourceTransactionManager.
Ik zie nu dat de oude code dat ook deed. Daar klopte dat ook niet, dus.

2022-01-21 15:20 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java
> +			case NARAYANA:
Dat klopt! Was gelukkig maar een kleine fix

2022-01-21 16:32 UTC, gvanbrakel commented
Punt van aandacht: in TransactionManagerTestBase is het itereren over de transactie managers uitgeschakeld, dat moet weer aan

2022-01-21 21:02 UTC, nielsm5 commented
> Punt van aandacht: in TransactionManagerTestBase is het itereren over de transactie managers uitgeschakeld, dat moet weer aan

Dat werkt niet lekker :(

2022-01-26 09:29 UTC, nielsm5 reviewed
Approve

2022-01-26 09:54 UTC, gvanbrakel approved these changes

2022-01-26 09:54 UTC, merged