Small fixes in gui
ibissource/iaf pull request #2698
Opened 2022-02-01 11:34 UTC by alisihab

Closes #2692

2022-02-01 11:48 UTC, nielsm5 approved these changes

2022-02-02 07:22 UTC, gvanbrakel requested changes

2022-02-02 07:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java
> +			matches += (iterItem.getInsertDate().after(startDate) || iterItem.getInsertDate().equals(startDate)) ? 1 : 0;
it would be more efficient to program this after-or-equal as not-before

2022-02-02 08:14 UTC, gvanbrakel approved these changes

2022-02-02 13:43 UTC, merged