Add dockerfile for activemq-artemis
ibissource/iaf pull request #2730
Opened 2022-02-08 09:46 UTC by alisihab

2022-02-16 19:53 UTC, nielsm5 requested changes

2022-02-16 19:53 UTC, nielsm5 commented on core/src/main/resources/META-INF/services/javax.json.spi.JsonProvider
> +org.glassfish.json.JsonProviderImpl
Goede werken! Misschien deze ook in de webapp module zetten.

2022-02-22 07:18 UTC, gvanbrakel requested changes

2022-02-22 07:18 UTC, gvanbrakel commented on test/src/main/webapp/META-INF/context.xml
> +		brokerURL="tcp://host.docker.internal:61615"
Here you use port 61615, while you published port 61616. I don't think that is close enough!

2022-02-22 10:20 UTC, gvanbrakel approved these changes

2022-03-09 12:32 UTC, nielsm5 approved these changes

2022-03-09 12:32 UTC, merged