Introduction of Message Context
ibissource/iaf pull request #2746
Opened 2022-02-10 17:29 UTC by gvanbrakel

2022-02-11 11:24 UTC, nielsm5 requested changes

2022-02-11 12:31 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/stream/Message.java
> +	public static final String METADATA_LOCATION = "Metadata.Location";
ok

2022-02-11 12:31 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/stream/UrlMessage.java
> +		super(() -> url.openStream(),  new MessageContext(context).withName(url.toString()), url.getClass());
ok

2022-02-16 10:50 UTC, nielsm5 approved these changes

2022-02-16 10:50 UTC, merged