Update URLs
ibissource/iaf pull request #2766
Opened 2022-02-16 09:57 UTC by ricardovh

2022-02-16 10:43 UTC, ricardovh commented
There are still some references to ibissource.org that could not yet be removed (https://ibissource.org/iaf/releases/, https://ibissource.org/contact/, https://ibissource.org/, http://maven.ibissource.org/iaf/, //ibissource.org)

2022-02-16 10:55 UTC, nielsm5 commented on README.md
> +[![Latest Snapshot](https://img.shields.io/nexus/public/org.ibissource/ibis-adapterframework-core?label=Latest%20Snapshot&server=https%3A%2F%2Fnexus.frankframework.org%2F)](https://nexus.frankframewo
https://nexus.frankframework.org/#browse/browse

2022-02-16 10:57 UTC, nielsm5 requested changes

2022-02-16 10:57 UTC, nielsm5 commented on pom.xml
>  		<url>https://ibissource.org</url>
```suggestion
		<name>Frank!Framework</name>
		<url>https://frankframework.org</url>
```

2022-02-16 10:58 UTC, nielsm5 commented
http://maven.ibissource.org/iaf/ mag gewoon https://frankframework.org worden.

2022-03-25 08:34 UTC, nielsm5 approved these changes

2022-03-25 09:57 UTC, gvanbrakel approved these changes

2022-03-25 09:57 UTC, merged