modern metrics collection
ibissource/iaf pull request #2777
Opened 2022-02-17 15:20 UTC by gvanbrakel

2022-02-18 13:27 UTC, nielsm5 requested changes

2022-02-18 14:09 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/statistics/StatisticsKeeper.java
> +	public Map<String, Object> asMap() {
Mijn idee was om daar waar het gebruikt wordt geen kennis te hoeven hebben van de internals van StatisticsKeeper

2022-02-21 09:50 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/statistics/StatisticsKeeper.java
> +	public Map<String, Object> asMap() {
Ja maar dan riskeer je wel dat andere er ook gebruik van gaan maken, en dat is niet de bedoeling.

2022-02-21 09:51 UTC, nielsm5 approved these changes

2022-02-21 09:52 UTC, merged