Create suppress key for xslt streaming warning
ibissource/iaf pull request #2805
Opened 2022-02-24 09:07 UTC by alisihab

Closes #2775

2022-02-24 10:17 UTC, gvanbrakel requested changes

2022-02-24 10:17 UTC, gvanbrakel commented on core/src/main/resources/AppConstants.properties
> +# If desired, xsltVersion can be set for the individual pipe.
This is a confusing comment if you put is this way. Please first explain/document the property as it is, and then note the exception

2022-02-24 13:04 UTC, nielsm5 commented on core/src/main/resources/AppConstants.properties
> +# If desired, xsltVersion can be set for the individual pipe.
```suggestion
# Sets the default XSLT version throughout the entire application except the ForEachChildElementPipe.
# The ForEachChildElementPipe usually works with large files and thus is streaming preferred.
# Currently streaming is only supported with XSLT version 1.
# Therefore this property will not change the XSLT version in the ForEachChildElementPipe.
# If desired, the XSLT version can be change for each individual ForEachChildElementPipe using xsltVersion=2.
```

2022-02-24 13:04 UTC, nielsm5 commented on core/src/main/resources/AppConstants.properties
> +# If desired, xsltVersion can be set for the individual pipe.
```suggestion
# Sets the default XSLT version throughout the entire application except the ForEachChildElementPipe.
# The ForEachChildElementPipe usually works with large files and thus is streaming preferred.
# Currently streaming is only supported with XSLT version 1.
# Therefore this property will not change the XSLT version in the ForEachChildElementPipe.
# If desired, the XSLT version can be change for each individual ForEachChildElementPipe using xsltVersion=2.
```

2022-02-24 16:03 UTC, gvanbrakel commented
Could you provide a backport to 7.7 too?

2022-02-24 16:04 UTC, gvanbrakel approved these changes

2022-03-07 13:58 UTC, nielsm5 approved these changes

2022-03-07 14:00 UTC, merged