Add getSchema and Websphere JNDI for PostgreSQL
ibissource/iaf pull request #2826
Opened 2022-03-04 10:34 UTC by ricardovh

Currently draft as PostgreSQL on Tomcat only works for BTM.

2022-03-04 10:36 UTC, ricardovh commented
Currently draft as PostgreSQL on Tomcat only works with BTM.

Narayana and default transaction manager give class cast exceptions:
Error creating bean with name 'ibisManager' defined in class path resource [springUnmanagedDeployment.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txManagerReal' defined in class path resource [springTOMCATNARAYANA.xml]: Cannot resolve reference to bean 'narayanaTransactionManager' while setting bean property 'transactionManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultDataSource' defined in class path resource [springTOMCAT.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'getDataSource' threw exception; nested exception is java.lang.ClassCastException: org.postgresql.xa.PGXADataSource cannot be cast to javax.sql.DataSource

2022-03-09 12:25 UTC, nielsm5 commented on test/src/main/webapp/META-INF/context.xml
> +		type="javax.sql.XADataSource"
is het echt nodig een XA datasource te gebruiken? kan je een PGDataSourceFactory gebruiken?

2022-03-15 12:13 UTC, gvanbrakel requested changes

2022-03-15 12:56 UTC, ricardovh commented on test/src/main/webapp/META-INF/context.xml
> +		username="${testiaf_user/username:-testiaf_user}"
It does not pick up the testiaf_user if attribute `user` is used, it uses `tomcat` instead of the testiaf_user.

2022-03-18 07:20 UTC, gvanbrakel commented on test/src/main/webapp/META-INF/context.xml
> +		username="${testiaf_user/username:-testiaf_user}"
Strange. "It works on my machine"

2022-03-18 12:48 UTC, ricardovh commented on test/src/main/webapp/META-INF/context.xml
> +		username="${testiaf_user/username:-testiaf_user}"
No, tried with master, gives the same issue.

Looking at the documentation of Tomcat, username is the correct attribute: https://tomcat.apache.org/tomcat-8.5-doc/jndi-datasource-examples-howto.html#PostgreSQL

2022-03-18 16:03 UTC, gvanbrakel commented on test/src/main/webapp/META-INF/context.xml
> +		username="${testiaf_user/username:-testiaf_user}"
Still strange, but vooruit dan maar

2022-03-24 07:45 UTC, gvanbrakel approved these changes

2022-03-24 07:46 UTC, merged