Add Artemis to Docker application servers for test
ibissource/iaf pull request #2882
Opened 2022-03-16 15:52 UTC by ricardovh

2022-03-18 10:38 UTC, ricardovh commented
Requires #2886 to be fixed, otherwise Larva tests fail

2022-03-31 11:43 UTC, ricardovh commented
> Requires #2886 to be fixed, otherwise Larva tests fail

As discussed with Niels(and also indicated in the issue), solved by using a replace on the property

2022-04-07 06:36 UTC, gvanbrakel requested changes

2022-04-07 06:36 UTC, gvanbrakel commented on docker/appserver/WebSphere/src/scripts/configureJvmProperties.py
> +setJVMSystemProperty( 'dtap.side', 'Docker')
Ik denk dat we van 'dtap.side' niet iets 'officieels' moeten maken

2022-04-07 06:36 UTC, gvanbrakel commented on docker/pom.xml
> +		<!-- ActiveMQ Artemis v2.19 is the latest that works with Java 8 -->
```suggestion
		<!-- ActiveMQ Artemis v2.19 is the last that works with Java 8 -->
```

2022-04-07 06:36 UTC, gvanbrakel commented on test/src/main/resources/SideSpecifics_Docker.properties
> +jms.destination.i4testiaf_out=jms/i4testiaf_out-${jms.provider.default}
Ik denk dat ik liever een variabele 'jms.destination.suffix' zie, dan deze definities via SideSpecifics

2022-04-19 11:31 UTC, gvanbrakel approved these changes

2022-04-19 14:25 UTC, nielsm5 approved these changes

2022-04-19 14:25 UTC, nielsm5 commented on docker/appserver/WebSphere/src/scripts/configureJms.py
> +createGenericJMSDestination('Artemis', 'i4testiaf_ff-activemq-artemis', 'jms/i4testiaf_ff-activemq-artemis', 'dynamicQueues/Q.TEST.FF')
ik denk dat we beter gewoon artemis kunnen gebruiken ipv activemq-artemis

2022-04-20 08:36 UTC, gvanbrakel approved these changes

2022-04-20 09:22 UTC, merged