Display resolved property value with placeholder
ibissource/iaf pull request #2894
Opened 2022-03-21 08:24 UTC by alisihab

Closes #2760

2022-03-22 08:27 UTC, gvanbrakel requested changes

2022-03-22 08:27 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/StringResolver.java
> +	public static String substVars(String val, Map props1, Map props2, List<String> propsToHide, String delimStart, String delimStop, boolean displayWithValue) throws IllegalArgumentException {
displayWithValue should be: resolveWithPropertyName

2022-03-24 13:40 UTC, nielsm5 requested changes

2022-03-24 13:40 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/util/StringResolverTest.java
>  	}
Can you also add a test when it cannot resolve the property? Aka there wont be a default value

2022-03-24 13:40 UTC, nielsm5 commented on core/src/test/resources/StringResolver.properties
> +mfh=${testdata}/mfh
Can you also add a property with a default value, so we can test that the framework can parse them without the `resolveWithPropertyName` flag enabled.

2022-03-28 13:45 UTC, nielsm5 requested changes

2022-04-01 11:27 UTC, nielsm5 requested changes

2022-04-01 11:27 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/StringResolver.java
> +	private static String extractKeyValue(String key, String delimStart, String delimStop, String defualtValueSeparator) {
oops I just noticed a typo: default

2022-04-01 11:27 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/xml/AttributePropertyResolver.java
> +		super.startElement(uri, localName, qName, new AttributesWrapper(attributes, v->StringResolver.substVars(v, properties, null, propsToHide, true)));
Could you add a property to enable/disable this, with the default being off?

2022-04-04 13:17 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/xml/AttributePropertyResolver.java
> +	private static final boolean resolveWithPropertyName = AppConstants.getInstance().getBoolean("properties.display.name", false);
```suggestion
	private static final boolean resolveWithPropertyName = AppConstants.getInstance().getBoolean("properties.resolve.withName", false);
```

2022-04-04 15:18 UTC, nielsm5 approved these changes

2022-04-05 08:17 UTC, gvanbrakel approved these changes

2022-04-05 08:17 UTC, merged