Fix MSSQL container init by not waiting fixed sleep time that might be insufficient
ibissource/iaf pull request #2898
Opened 2022-03-21 10:28 UTC by ricardovh

2022-03-21 16:06 UTC, gvanbrakel requested changes

2022-03-21 16:06 UTC, gvanbrakel commented on docker/dbms/MsSqlServer/dockerInit.sh
> +		        sleep 1
```suggestion
		        if [[ $i == 120 ]]
		        then
		                echo "WARN: timeout in create_user"
		                break
		        else         
		                sleep 1
		        fi
```

2022-03-22 08:13 UTC, gvanbrakel approved these changes

2022-03-24 13:53 UTC, nielsm5 approved these changes

2022-03-24 13:53 UTC, merged