Issue/2896 xml validator should recover from recoverable errors
ibissource/iaf pull request #2918
Opened 2022-03-23 14:57 UTC by gvanbrakel

2022-03-24 10:45 UTC, nielsm5 requested changes

2022-03-24 10:45 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/validation/AbstractXmlValidator.java
> +		return ValidationResult.VALID;
ik zou bijna zeggen dat de handleFailures zelf de ErrorHandler op zou kunnen halen, en dan een result te bedenken.
Misschien is het het mooist om `handleFailures` te hernoemen naar `finalizeValidation` zodat het een overloaded methode wordt. Dan past het meer bij elkaar (en dan ook de methodes bij elkaar zetten)

2022-03-24 10:45 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
> + * @ff.forward warnings warnings occurred. If not specified, <code>success</code> is used.
singular van maken? het is ook niet failures/outputFailures ?

2022-03-24 10:45 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/senders/XmlValidatorSender.java
> +			if (validationResult == ValidationResult.VALID || validationResult == ValidationResult.VALID_WITH_WARNINGS) {
Moet deze ook door als hij valid with warnings is, of alleen als recoverFromRecoverableErrors is gezet?

2022-03-24 11:56 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/align/XmlAligner.java
> +	private @Getter @Setter boolean recoverFromRecoverableErrors=false;
Het kan dus ook zonder ...

2022-03-28 08:19 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
> +		//aligner.setIgnoreUndeclaredElements(isIgnoreUndeclaredElements()); // cannot ignore XML Schema Validation failure in this case, currently
misschien is het handig voor de forward compatibiliteit om in de configure te zorgen dat je een warning/error krijgt wanneer je dit zet bij XML2JSON.

2022-03-28 09:30 UTC, nielsm5 approved these changes

2022-03-28 09:35 UTC, merged