Fix warning attribute name must appear on XmlInputValidator
ibissource/iaf pull request #2922
Opened 2022-03-24 11:40 UTC by mhdirkse

2022-03-24 11:43 UTC, mhdirkse commented
Should fix Frank!Doc issue https://github.com/ibissource/frank-doc/issues/91.

2022-03-24 11:46 UTC, gvanbrakel requested changes

2022-03-24 11:46 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
> +		@Optional
This change should not be necessary, as the ` @Optional` annotation should be inherited from `IValidator`

2022-03-25 16:57 UTC, gvanbrakel commented
problem will be solved in frank doc generator

2022-03-25 16:57 UTC, closed without merging