Introduce connection overview page
ibissource/iaf pull request #2929
Opened 2022-03-25 15:38 UTC by alisihab

Closes #2430

2022-03-25 17:43 UTC, nielsm5 commented
Perhaps you can make the icon blue, nice arrow icon btw!
Overview looks good

2022-03-28 08:38 UTC, nielsm5 approved these changes

2022-03-28 09:13 UTC, gvanbrakel requested changes

2022-03-28 09:13 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemSenderTest.java
> +			}
This should not be necessary, the domain of the MockFileSystem should be used

2022-03-28 09:13 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemPipeTest.java
> +			}
This should not be necessary, the domain of the MockFileSystem should be used

2022-03-28 09:13 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemListenerTest.java
> +			}
This should not be necessary, the domain of the MockFileSystem should be used

2022-03-29 08:02 UTC, gvanbrakel requested changes

2022-03-29 08:02 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystem.java
> +	private final @Getter(onMethod = @__(@Override)) String domain = "Filesystem";
```suggestion
	private final @Getter(onMethod = @__(@Override)) String domain = "MockFilesystem";
```

2022-03-29 08:02 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemSenderTest.java
> +		FileSystemSender<MockFile,MockFileSystem<MockFile>> result=new FileSystemSender<MockFile,MockFileSystem<MockFile>>() {};
```suggestion
		FileSystemSender<MockFile,MockFileSystem<MockFile>> result=new FileSystemSender<MockFile,MockFileSystem<MockFile>>();
```

2022-03-29 09:18 UTC, alisihab commented on core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemSenderTest.java
> +		FileSystemSender<MockFile,MockFileSystem<MockFile>> result=new FileSystemSender<MockFile,MockFileSystem<MockFile>>() {};
FileSystemSender is an abstract class

2022-03-30 12:12 UTC, merged