LCM upgrade jackson dependencies
ibissource/iaf pull request #2935
Opened 2022-03-28 14:41 UTC by alisihab

2022-03-28 15:34 UTC, nielsm5 approved these changes

2022-03-29 07:45 UTC, gvanbrakel requested changes

2022-03-29 07:45 UTC, gvanbrakel commented on core/pom.xml
> +			<version>2.13.2.1</version> <!-- patch release -->
I think I prefer to have a property `jackson.databind.version`, to assure that future versions will keep in sync too

2022-03-29 09:51 UTC, gvanbrakel approved these changes

2022-03-30 11:07 UTC, merged