Don't unregister non-registered resources
ibissource/iaf pull request #3039
Opened 2022-04-08 07:44 UTC by nielsm5

2022-04-08 16:00 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> -						}
Toch niet

2022-04-11 10:57 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> -						}
nope!

2022-04-11 13:52 UTC, gvanbrakel requested changes

2022-04-11 13:52 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> -						}
en waarom dan niet?

2022-04-11 14:09 UTC, gvanbrakel approved these changes

2022-04-11 14:37 UTC, merged