Stop support for httpRequest parameter in larva
ibissource/iaf pull request #3057
Opened 2022-04-13 09:45 UTC by alisihab

Closes #2975

2022-04-13 10:22 UTC, gvanbrakel requested changes

2022-04-13 10:22 UTC, gvanbrakel commented on larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
> +				/** httpRequest parameter is only used in CreateRestViewPipe. It is unlikely to create a larva test for this pipe */
Please add the reason why support has been removed

2022-04-14 12:32 UTC, nielsm5 approved these changes

2022-04-15 07:58 UTC, nielsm5 approved these changes

2022-04-15 08:35 UTC, merged