Always store IbisContext in ServletConfig
ibissource/iaf pull request #3067
Opened 2022-04-14 14:29 UTC by nielsm5

2022-04-14 16:13 UTC, gvanbrakel requested changes

2022-04-14 16:13 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
> +			t = ibisContext.getStartupException();
```suggestion
			t = ibisContext.getStartupException();
			throw new IllegalStateException("Could not start ibis", t);
```

2022-04-15 07:41 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
> +			t = ibisContext.getStartupException();
Ik denk niet dat dit nodig/nuttig is.

2022-04-15 09:08 UTC, gvanbrakel requested changes

2022-04-15 09:08 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
> +	private static final String EXCEPTION_KEY = "StartupException";
Je moet dan ook KEY_CONTEXT en KEY_EXCEPTION uit AppConstants halen

2022-04-19 06:46 UTC, gvanbrakel requested changes

2022-04-19 06:46 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +			throw new ApiException(e, 404);//why 404 when there clearly is something else going on?
maak er dan 500 van

2022-04-19 13:48 UTC, gvanbrakel approved these changes

2022-04-19 13:48 UTC, merged