Fix uri encoding for component names
ibissource/iaf pull request #3191
Opened 2022-05-17 09:36 UTC by alisihab

Closes #3175

2022-05-18 06:33 UTC, gvanbrakel requested changes

2022-05-18 06:33 UTC, gvanbrakel commented on webapp/src/main/webapp/iaf/gui/js/services.js
> +			return encodeURIComponent(encodeURIComponent(uri));
It should not be necessary to just double encode all uris.

2022-05-18 06:33 UTC, gvanbrakel commented on webapp/src/main/webapp/iaf/gui/js/services.js
> +			return encodeURIComponent(encodeURIComponent(uri));
It should not be necessary to just double encode all uris.

2022-05-18 06:33 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java
> +			if (name.equals(adapter.getName()) || adapter.getName().equals(Misc.urlDecode(name))) {
It should not be necessary to explicitly decode adapternames here

2022-05-18 06:33 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java
> +			if (name.equals(adapter.getName()) || adapter.getName().equals(Misc.urlDecode(name))) {
It should not be necessary to explicitly decode adapternames here

2022-05-18 06:33 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java
> +				getIbisManager().handleAction(action, "", adapter.getName(), null, getUserPrincipalName(), false);
Could the name have changed?

2022-05-18 06:33 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java
> +				getIbisManager().handleAction(action, "", adapter.getName(), null, getUserPrincipalName(), false);
Could the name have changed?

2022-05-18 09:00 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
> +			pipe = pipesByName.get(Misc.urlDecode(pipeName));
As discussed, there should be no urlDecode() in PipeLine

2022-05-30 15:27 UTC, nielsm5 commented
[a-zA-z0-9]

2022-05-31 12:09 UTC, jjansenvr commented
We decided not to double escape any names of adapters, pipes and listeners, 

Can you please add the ConfigurationException equivalents to the other names

2022-06-02 14:06 UTC, nielsm5 approved these changes

2022-06-02 14:25 UTC, merged