Use scenario specific correlationId in Larva
ibissource/iaf pull request #3215
Opened 2022-05-19 12:48 UTC by alisihab

Closes #2989

2022-05-19 14:13 UTC, gvanbrakel requested changes

2022-05-19 15:37 UTC, gvanbrakel requested changes

2022-05-19 15:37 UTC, gvanbrakel commented on larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
> +	private static int executeSenderWrite(String stepDisplayName, Map<String, Map<String, Object>> queues, Map<String, Object> writers, String queueName, String senderType, String fileContent, String ge
Please rename this parameter generatedCorrelationId also to correlationId

2022-05-19 15:37 UTC, gvanbrakel commented on larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
> +	private static int executeFixedQuerySenderRead(String step, String stepDisplayName, Properties properties, Map<String, Map<String, Object>> queues, Map<String, Object> writers, String queueName, Str
Please rename this parameter generatedCorrelationId also to correlationId

2022-05-19 15:37 UTC, gvanbrakel commented on larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
> +	public static int executeStep(String step, Properties properties, String stepDisplayName, Map<String, Map<String, Object>> queues, Map<String, Object> writers, int parameterTimeout, String generated
Please rename this parameter generatedCorrelationId also to correlationId

2022-05-19 15:58 UTC, gvanbrakel approved these changes

2022-05-20 08:19 UTC, nielsm5 approved these changes

2022-05-20 08:29 UTC, merged