Backport #2685: Maven CI friendly versions (7.7)
ibissource/iaf pull request #3261
Opened 2022-05-25 13:12 UTC by ricardovh

2022-05-27 08:42 UTC, nielsm5 requested changes

2022-05-27 08:42 UTC, nielsm5 commented on pom.xml
> +							<?m2e ignore?>
Als Eclipse hier echt over zeurt moet je de `<groupId>org.eclipse.m2e</groupId> ... <artifactId>lifecycle-mapping</artifactId>` overnemen uit de master. De `<?m2e ignore?>` mag niet op maven central staan...

2022-05-27 08:42 UTC, nielsm5 commented on docker/pom.xml
> +		<iaf.version>${revision}</iaf.version>
Is deze nu nog nodig?

2022-06-01 09:05 UTC, nielsm5 approved these changes

2022-06-02 12:08 UTC, gvanbrakel approved these changes

2022-06-02 12:09 UTC, merged