Update originalBlock session key once for each block in BatchFileTransformerPipe
ibissource/iaf pull request #3312
Opened 2022-06-08 10:46 UTC by alisihab

Closes #3260

2022-06-08 13:16 UTC, gvanbrakel requested changes

2022-06-08 13:16 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/batch/IResultHandler.java
> +	void closeBlock(PipeLineSession session, String streamId, String blockName, Map<String, Object> blocks) throws Exception;
Is the session parameter really used somewhere? Can it be removed?

2022-06-10 07:22 UTC, gvanbrakel approved these changes

2022-06-10 10:07 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/batch/BatchFileTransformerPipe.java
> +			throw new PipeRunException(this, "could not get message ["+input+"] as String", e);
```suggestion
			throw new PipeRunException(this, "could not read message ["+input+"] as String", e);
```

2022-06-10 10:07 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/batch/BatchFileTransformerPipe.java
> +			throw new PipeRunException(this, "could not get message ["+input+"] as String", e);
```suggestion
			throw new PipeRunException(this, "could not read message ["+input+"] as String", e);
```

2022-06-10 10:07 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/batch/BatchFileTransformerPipe.java
> +			log.error("Could not get message ["+input+"] as String");
```suggestion
			log.error("Could not read message ["+input+"] as String");
```

2022-06-10 12:10 UTC, nielsm5 approved these changes

2022-06-10 12:11 UTC, merged