WildFly Test image
ibissource/iaf pull request #3315
Opened 2022-06-08 14:48 UTC by ricardovh

2022-06-15 06:48 UTC, gvanbrakel requested changes

2022-06-15 06:48 UTC, gvanbrakel commented on docker/appserver/WildFly/.project
> +	<name>ibis-adapterframework-docker-as-wildfly</name>
```suggestion
	<name>iaf-docker-as-WildFly</name>
```

2022-06-16 06:36 UTC, gvanbrakel approved these changes

2022-06-17 08:04 UTC, nielsm5 approved these changes

2022-06-17 08:28 UTC, merged