Fix disable template in stubbing xsl
ibissource/iaf pull request #3328
Opened 2022-06-10 06:33 UTC by alisihab

Closes #2849

2022-06-10 07:17 UTC, gvanbrakel approved these changes

2022-06-10 09:58 UTC, nielsm5 requested changes
Is it possible to also test the commented section  `<!--` ... `-->` ?

2022-06-10 12:10 UTC, nielsm5 approved these changes

2022-06-10 13:05 UTC, gvanbrakel requested changes

2022-06-10 13:05 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java
> +		MatchUtils.assertXmlEquals(null, expectedConfiguration, actual, false, true);
This test does not test for the current problem situation: that the produced stream looks like XML with comments, but the events from which it is produced do not have the stubbed commented out

2022-06-10 14:40 UTC, gvanbrakel requested changes

2022-06-10 14:40 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java
> +			}
You should also override startElement() and check that there is not a listener element with className EsbJmsListener

2022-06-13 09:45 UTC, gvanbrakel approved these changes

2022-06-13 09:46 UTC, merged