Fix splitting requestUrl in openApi schema generation
ibissource/iaf pull request #3345
Opened 2022-06-13 13:36 UTC by alisihab

Closes #3290

2022-06-13 13:46 UTC, gvanbrakel requested changes

2022-06-13 13:46 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
> +			requestUrl = Misc.urlDecode(requestUrl); // request url from browser might be encoded
I assume this solves the problem? It would be wise to include a test using an encoded requestUrl

2022-06-16 06:33 UTC, gvanbrakel approved these changes

2022-06-17 13:34 UTC, nielsm5 reviewed
It's just the request url that's giving issues, there is no need to display/put the curly braces in the url. I also noticed the url contains the path twice? See `hello-world/hello-world_GET_openapi.json` maybe that can also be simplified? Unless I'm missing something here, I feel like this solution is making it more complex that it shoud be, escaping the url will make it less readable, see `hello-world/%7Bmy-var%7D/hello-world_%7Bmy-var%7D_GET_openapi.json`

2022-06-20 07:57 UTC, gvanbrakel requested changes

2022-06-20 07:57 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
> +import nl.nn.credentialprovider.util.Misc;
could you correct the packagename?

2022-06-20 09:36 UTC, gvanbrakel approved these changes

2022-06-20 10:45 UTC, merged