Create symbolic links in docker image, so original files wont change ownership
ibissource/iaf pull request #3450
Opened 2022-06-30 10:04 UTC by philipsens

2022-06-30 11:10 UTC, ricardovh requested changes
Kan je ook de example en test Dockerfiles aanpassen om de nieuwe directories te gebruiken?

2022-06-30 12:26 UTC, philipsens commented on Docker.md
> +Files that are copied or mounted to `/frank` will be linked to `/opt/frank`. `/opt/frank` will change ownership to the user `tomcat`. This is done as part of running the container as [non-root](#Non-
Dus met het commentaar van hieronder is het goed. Verwijderen en klaar?

2022-06-30 12:26 UTC, philipsens commented on Docker.md
> +Files that are copied or mounted to `/frank` will be linked to `/opt/frank`. `/opt/frank` will change ownership to the user `tomcat`. This is done as part of running the container as [non-root](#Non-
Doelt dit op de tabel of heel de paraaf?

2022-06-30 12:29 UTC, philipsens commented on Docker.md
>  ## Permissions
Ik heb het getest en het werkt naar behoren. Ik denk dat de vermelding over start-up performance wel nuttig is.

2022-06-30 12:40 UTC, philipsens commented on Docker.md
>  ## Permissions
Test of het script überhaupt nodig is.
In de Dockerfile de owner van de link veranderen. Kijk of dat genoeg is.

2022-06-30 12:46 UTC, philipsens commented on Docker.md
>  ## Non-root
Zie boven

2022-06-30 12:49 UTC, gvanbrakel requested changes
Ik zou willen voorstellen om de directory waar gebruikers hun spullen neerzetten '/opt/frank' te houden, en intern een andere directory te gaan gebruiken, bijvoorbeeld '/opt/frank-internal/. 
Zo blijft '/opt/frank' voor gebruikers constant en herkenbaar.

2022-07-01 07:14 UTC, gvanbrakel requested changes

2022-07-01 07:14 UTC, gvanbrakel commented on Docker.md
> +	-v $pwd/example/src/main/resources:/frank/resources \
```suggestion
	-v $pwd/example/src/main/resources:/opt/frank/resources \
```

2022-07-01 07:14 UTC, gvanbrakel commented on Docker.md
> +| /frank/secrets | Credential storage | See [Secrets](#Secrets) |
```suggestion
| /opt/frank/secrets | Credential storage | See [Secrets](#Secrets) |
```

2022-07-01 08:17 UTC, nielsm5 commented on docker/appserver/Tomcat/Dockerfile
> +USER tomcat
hier nog een commentaartje ;)

2022-07-01 08:18 UTC, gvanbrakel requested changes
Goede aanpassing!
Zou je ook in alle .bat scripts `--mount type=bind,source=` kunnen vervangen door `-v ` en `,target=` door `:`?

2022-07-01 13:58 UTC, gvanbrakel approved these changes

2022-07-01 15:02 UTC, nielsm5 approved these changes

2022-07-04 10:42 UTC, merged