introduction of status recording NarayanaJtaTransactionManager
ibissource/iaf pull request #3594
Opened 2022-08-23 13:37 UTC by gvanbrakel

2022-08-24 08:09 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/jta/narayana/NarayanaJtaTransactionManagerTest.java
> +	@Ignore("For a proper test, we need to set up a transaction that cannot be completed or rolled back")
Het zou gaaf zijn als btm en narayana de zelfde baseclass kunnen gebruiken.

Ik zie hier, en bij BTM een ignore. Testen we dit wel goed want hier gaat het natuurlijk eigenlijk om..

2022-09-01 13:50 UTC, nielsm5 requested changes

2022-09-01 13:50 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/Locker.java
> -	}
is dit wel handig, moet hier niet frank/java-doc bij?

2022-09-01 13:50 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/jdbc/dbms/TestBlobs.java
> +@Ignore("Tests for Blobs take much too time and memory to test regularly")
```suggestion
@Ignore("Tests for Blobs take too much time and memory to test regularly")
```

2022-09-01 13:50 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/testutil/TransactionManagerType.java
> -		}
waarom haal je dit nou weg?

2022-09-01 13:50 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManagerImplementationTest.java
> +	}
Het was niet modelijk de StatusRecordingTransactionManagerTestBase de TransactionManagerTestBase te extenden?

2022-09-01 16:20 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/testutil/TransactionManagerType.java
> -		}
omdat hij dan toch wel failt als gevolg van de exceptie

2022-09-02 10:00 UTC, nielsm5 approved these changes

2022-09-02 11:10 UTC, merged