Migrate configuration management to the bus
ibissource/iaf pull request #3773
Opened 2022-09-27 15:51 UTC by nielsm5

2022-09-28 06:18 UTC, gvanbrakel requested changes

2022-09-28 06:18 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ConfigManagement.java
> +	@ActionSelector("xml")
'xml' is een formaat, geen actie. Moet het niet 'retrieve' of 'download' zijn?

2022-09-28 06:18 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ConfigManagement.java
> +	@ActionSelector("details")
Welke details krijg je hier?

2022-09-28 11:30 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ConfigManagement.java
> +	@ActionSelector("details")
find

2022-09-28 14:29 UTC, gvanbrakel requested changes

2022-09-28 14:29 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ConfigManagement.java
> +	@ActionSelector("get")
Kunnen de actions constanten worden, die ook in de 'frontend' zoals ShowConfiguration gebruikt kunnen worden?

2022-09-29 12:08 UTC, gvanbrakel approved these changes

2022-09-29 12:47 UTC, merged