refactor build scripts for WebSphere, JBoss and WildFly
ibissource/iaf pull request #3805
Opened 2022-09-30 15:11 UTC by gvanbrakel

2022-10-03 07:33 UTC, ricardovh requested changes

2022-10-03 07:33 UTC, ricardovh commented on docker/scripts/setenv.bat
> +set MVN=C:\opt\Apache\Maven\apache-maven-3.8.3\bin\mvn
Eigenlijk is deze (en JAVA_HOME als die niet al gezet is) de enige die per gebruiker anders zal zijn, die in een aparte setlocalenv.bat zetten en die in de .gitignore zetten?

2022-10-04 06:59 UTC, gvanbrakel commented on docker/scripts/setenv.bat
> +set CLI_OPTS=-Dmaven.wagon.http.ssl.insecure=true
ok

2022-10-04 06:59 UTC, gvanbrakel commented on docker/appserver/scripts/build-start-body.bat
> +docker volume prune --force
ok, verplaatst naar clean_iaf.bat, en daar uitgecomment

2022-10-04 07:05 UTC, gvanbrakel commented on docker/appserver/scripts/build-start-body.bat
> +call %MVN% %CLI_OPTS% -f %~dp0/../../.. -s "%MVN_SETTINGS%" install -DskipTests=true
idd

2022-10-12 07:23 UTC, ricardovh approved these changes

2022-10-13 11:50 UTC, merged

2022-10-13 11:51 UTC, nielsm5 commented
Tja, ik zou het zelf niet gebruiken...