Document labels
ibissource/iaf pull request #3844
Opened 2022-10-11 14:26 UTC by mhdirkse

2022-10-11 15:15 UTC, gvanbrakel requested changes

2022-10-11 15:15 UTC, gvanbrakel commented on FRANKDOC.md
> +| - | `@Label` | Java Annotation | When the target annotation is placed on a Java class, a label is added in the Frank!Doc webapp. The value of the label is the `value()` field of the target annotati
Ik denk dat het goed is om als voorbeeld te verwijzen naar `@Category`

2022-10-18 07:39 UTC, gvanbrakel approved these changes

2022-10-18 07:39 UTC, nielsm5 approved these changes

2022-10-18 07:39 UTC, merged