Add Influx image and configuration
ibissource/iaf pull request #3887
Opened 2022-10-20 12:12 UTC by ricardovh

2022-10-20 15:20 UTC, gvanbrakel requested changes

2022-10-20 15:20 UTC, gvanbrakel commented on docker/appserver/WebSphere/src/configuration/01-configureAuthAlias.py
> +	createAuthAlias(aliasName, username, password)
Ik denk dat het goed is om na het creeren van de authAliases de secrets uit /opt/frank te deleten. (Ook bij anderen appservers)

2022-10-24 14:17 UTC, gvanbrakel approved these changes

2022-10-24 14:35 UTC, nielsm5 approved these changes

2022-10-24 14:36 UTC, merged