Migrate AdapterStatus
ibissource/iaf pull request #3930
Opened 2022-10-28 14:37 UTC by nielsm5

2022-10-31 09:59 UTC, gvanbrakel requested changes

2022-10-31 09:59 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java
> +		throw new ApiException("not implemented!");
Hoeft dit niet?

2022-10-31 09:59 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java
> +		throw new ApiException("not implemented!");
Hoeft dit niet?

2022-10-31 09:59 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java
> +		throw new ApiException("not implemented!");
Hoeft dit niet?

2022-10-31 13:01 UTC, gvanbrakel approved these changes

2022-11-01 07:49 UTC, merged

2022-11-07 10:21 UTC, nielsm5 commented
#3187