Update springIBISTEST with metricsRegistry bean
ibissource/iaf pull request #3961
Opened 2022-11-07 15:26 UTC by VBPham

2022-11-07 16:02 UTC, nielsm5 requested changes

2022-11-07 16:02 UTC, nielsm5 commented on core/src/main/resources/springIBISTEST.xml
> -
nog wel de `ref="ibisTestDataSource"` aanpassen naar `ref="h2DataSource"`

2022-11-14 09:10 UTC, nielsm5 approved these changes

2022-11-14 15:32 UTC, gvanbrakel approved these changes

2022-11-14 15:32 UTC, merged