Fix returning inputstream session keys
ibissource/iaf pull request #4008
Opened 2022-11-16 10:54 UTC by gvanbrakel

2022-11-18 15:38 UTC, nielsm5 requested changes

2022-11-18 15:38 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
> +		throw new RuntimeException("function of attribute 'isolated' is replaced by 'transactionAttribute' on PipeLine");
IllegalStateException, NotImplementedException of IllegalArgumentException?

2022-11-18 17:35 UTC, gvanbrakel commented
Er zijn nog iaf-test failures

2022-11-22 09:55 UTC, nielsm5 approved these changes

2022-11-22 10:00 UTC, merged