Create Micrometer Registry FactoryBean
ibissource/iaf pull request #4075
Opened 2022-11-25 10:52 UTC by nielsm5

2022-11-29 07:43 UTC, gvanbrakel requested changes

2022-11-29 07:43 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jndi/TransactionalDbmsSupportAwareDataSourceProxy.java
> +	private synchronized void populate(Connection connection) throws SQLException {
Met deze synchronized los je niet een 'half gevulde metadata' probleem op.
Daarvoor moet je eerst een locale metadata vullen, en die op het eind aan de globale assignen.
De synchronized voegt alleen een 'gevoel van veiligheid' toe.

2022-11-29 07:43 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
> +		if(parentContext == null) { //When not running in a web container, popularize beans so they can be found throughout this/sub-contexts.
popularize?

2022-11-29 17:30 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
> +		if(parentContext == null) { //When not running in a web container, popularize beans so they can be found throughout this/sub-contexts.
Tja, hele populaire boontjes...

2022-11-30 10:22 UTC, gvanbrakel requested changes

2022-11-30 10:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/jndi/TransactionalDbmsSupportAwareDataSourceProxy.java
> +	private synchronized void populateMetadata(Connection connection) throws SQLException {
Die synchronized kan weg volgens mij. Hij zorgt er nu voor dat de threads die metadata==null hebben gezien nu na elkaar de metadata op gaan halen. 
Het suggereert een gevoel van veiligheid, maar het houdt hier alleen maar op.

2022-11-30 10:22 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
> +		ClassLoader classLoader = classPathapplicationContext.getClassLoader();
```suggestion
		ClassLoader classLoader = classPathApplicationContext.getClassLoader();
```

2022-11-30 10:32 UTC, gvanbrakel approved these changes

2022-11-30 10:49 UTC, merged