Change CacheControl header to only work when no-etag is present
ibissource/iaf pull request #4284
Opened 2023-01-04 15:09 UTC by nielsm5

Supersedes #4050.

2023-01-05 09:02 UTC, gvanbrakel requested changes

2023-01-05 09:21 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +
If a Last Modified value is present, set the 'Last-Modified' header.
else, don't cache.

2023-01-05 09:24 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +				StringBuilder cacheControl = new StringBuilder();
```suggestion
				// If no eTag header is present, disable caching.
				StringBuilder cacheControl = new StringBuilder();
```

2023-01-05 09:25 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +				// If no eTag header is present, disable caching.
```suggestion
				// If no eTag header is present, disable browser caching. Else force browser to revalidate the request.
```

2023-01-06 07:51 UTC, gvanbrakel approved these changes

2023-01-06 09:01 UTC, merged