Issue/4282 junit5 migration
ibissource/iaf pull request #4292
Opened 2023-01-05 09:45 UTC by VBPham

This pull request can be summarized as follows

- update imports and rearrange parameters
- update method of working with tempdir 
- Update @ignore annotations to junit 5 @disabled annotations

- two (isolated) parameterized test in junit 5 style: ClassLoaderManagerTest & BusExceptionTest 

Tests that are left over are mostly from core, senders and pipes package. Lots of inheritance and parameterized tests

2023-01-05 10:23 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/align/TestMap2Xml.java
> +	@Disabled //("Map2XML does not support mixed content")
Waarom heb je hier de comments uit de annotatie gehaald?
```suggestion
	@Disabled("Map2XML does not support mixed content")
```

2023-01-05 10:29 UTC, VBPham commented on core/src/test/java/nl/nn/adapterframework/align/TestMap2Xml.java
> +	@Disabled //("Map2XML does not support mixed content")
ah, wist niet dat dat kon. Pas ik even aan

2023-01-06 14:05 UTC, nielsm5 approved these changes

2023-01-09 13:37 UTC, gvanbrakel requested changes

2023-01-09 13:37 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
> -		exception.expectMessage("fake owner of FileSystemActor");
Deze assertion moet ook gedaan worden

2023-01-09 13:37 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/align/TestDomTreeAligner.java
> +			boolean potentialCompactionProblems, String expectedFailureReason) throws Exception {
Dit mag op een regel blijven

2023-01-09 14:29 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/configuration/ClassLoaderManagerTest.java
> -		appConstants = AppConstants.getInstance();
Is verplaatst naar de setup

2023-01-09 14:30 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/configuration/ClassLoaderManagerTest.java
> +		configureClassloader(classLoader, configurationName);
Nee, niet in deze (junit5) setup

2023-01-09 14:47 UTC, gvanbrakel approved these changes

2023-01-09 15:39 UTC, merged