Fix missing message context headers on GET requests
ibissource/iaf pull request #4314
Opened 2023-01-09 16:30 UTC by nielsm5

2023-01-10 07:26 UTC, gvanbrakel commented
Heb je gezien dat de combinatie ApiListener / Json2XmlValidator nu goed werkt?

2023-01-10 13:13 UTC, gvanbrakel requested changes

2023-01-11 07:31 UTC, gvanbrakel requested changes

2023-01-11 07:31 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +				if(StringUtils.isNotBlank(acceptHeader) && !listener.accepts(acceptHeader)) { // If an Accept header is present, make sure we comply to it!
Ik denk dat er in de buurt van deze code nog zoiets moet komen dat als de ApiListener een Produces=JSON heeft, en er geen Accept-Header is, de Json2XmlValidator dan toch die JSON door krijgt. Dat hij dan een Accept-Header injeteert in de context, bijvoorbeeld

2023-01-11 08:48 UTC, gvanbrakel approved these changes

2023-01-11 12:05 UTC, tnleeuw approved these changes

2023-01-11 12:16 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
> +		assertEquals("application/xml", input.getContext().get("Header.accept"));
In the hope that if we change the constant, the test will fail (as it wont be backwards compatible anymore)

2023-01-11 12:17 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
> +					response.getWriter().print("It appears you expected the MediaType ["+acceptHeader+"] but I only support the MediaType ["+listener.getContentType()+"] :)");
Yup! Will do this (in another pr).

2023-01-11 12:27 UTC, merged