Backport of 'Migrate to new MySql maven project'
ibissource/iaf pull request #4338
Opened 2023-01-12 14:06 UTC by VBPham

mysql artefact has moved, was already fixed in master. Now added to 7.8 branch for proper testing of jenkin issues

2023-01-12 14:52 UTC, gvanbrakel submitted a review, later dismissed

2023-01-13 10:30 UTC, nielsm5 commented
Je hebt de versie niet aangepast, wat is er functioneel nou veranderd?

2023-01-13 12:10 UTC, gvanbrakel commented
> Je hebt de versie niet aangepast, wat is er functioneel nou veranderd?

Deze versie is niet meer onder de oude naam te vinden in externe repositories

2023-01-13 13:01 UTC, nielsm5 approved these changes
Houd er wel rekening mee dat voor de CI's en docker images die wij opleveren alleen de master branch versie daadwerkelijk gebruikt wordt. ~Er moet geen tijd gestoken worden in het fixen van docker images op oude versies.~ Ik snap dat de het verwarrend kan zijn, en dat is ook de reden de meeste projecten uit deze repo gehaald zijn.

Graag nog even het pr nummer refereren en de juiste labels toevoegen.

2023-01-13 13:23 UTC, gvanbrakel requested changes
De referentie in WebSphere/src/scripts/configureJdbc.py moet ook aangepast worden

2023-01-16 09:47 UTC, VBPham commented
Backport of #3903

2023-01-18 09:35 UTC, merged