Add debug logging
ibissource/iaf pull request #4394
Opened 2023-01-20 21:54 UTC by tnleeuw

Add debug logging to get more info on what is going on before the exception happens.

PR against 7.8 branch first since that was the version used for testing.

2023-01-23 16:16 UTC, gvanbrakel requested changes

2023-01-24 07:46 UTC, gvanbrakel approved these changes

2023-01-24 10:16 UTC, nielsm5 approved these changes
Nu om dit te debuggen is snap ik de vele log statements, maar misschien is het handig (zodra je de nieuwe log files hebt) te kijken welke statements trace en welke debug kunnen blijven.

2023-01-24 10:42 UTC, merged

2023-01-24 11:10 UTC, tnleeuw commented
> Nu om dit te debuggen is snap ik de vele log statements, maar misschien is het handig (zodra je de nieuwe log files hebt) te kijken welke statements trace en welke debug kunnen blijven.

Dat snap ik, ik was ook niet van plan om dit allemaal erin te laten!