Add FtpFileSystemListener
ibissource/iaf pull request #4445
Opened 2023-02-01 11:13 UTC by gvanbrakel

2023-02-01 17:23 UTC, nielsm5 requested changes

2023-02-01 17:23 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/FtpFileSystemListener.java
> +public class FtpFileSystemListener extends FileSystemListener<FTPFileRef, FtpFileSystem> implements HasKeystore, HasTruststore {
Kan je niet beter een Interface maken met defaults die bv.
```
@ReferTo(FtpFileSystem.class)
	public void setHost(String host) {
		getFileSystem().setHost(host);
	}
```
doet, en dan aan de sender en de listener het interface hangen?

2023-02-02 07:49 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/receivers/FtpFileSystemListener.java
> +public class FtpFileSystemListener extends FileSystemListener<FTPFileRef, FtpFileSystem> implements HasKeystore, HasTruststore {
Ik had het zelf willen verzinnen!

2023-02-03 16:14 UTC, nielsm5 approved these changes

2023-02-06 16:11 UTC, merged