4276 Fix recursive invocation of logger
ibissource/iaf pull request #4515
Opened 2023-02-16 10:32 UTC by tnleeuw

2023-02-17 07:21 UTC, gvanbrakel requested changes

2023-02-17 07:21 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/configuration/AdapterManager.java
> +		if (log.isDebugEnabled()) log.debug("registering adapter [" + adapter + "] with AdapterManager [" + this + "]");
Kan je hier een comment bij zetten waarom het hier zo moet? Anders staat het volgende week al weer net zo als het was.

2023-02-17 08:30 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/configuration/AdapterManager.java
> +		if (log.isDebugEnabled()) log.debug("registering adapter [" + adapter + "] with AdapterManager [" + this + "]");
Goed punt. Gedaan.

2023-02-17 15:28 UTC, nielsm5 requested changes

2023-02-17 15:28 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/configuration/AdapterManager.java
> +		if (log.isDebugEnabled()) log.debug("registering adapter [{}] with AdapterManager [{}", adapter.toString(), this.toString());
```suggestion
		if (log.isDebugEnabled()) log.debug("registering adapter [{}] with AdapterManager [{}]", adapter.toString(), this.toString());
```

2023-02-17 15:28 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/Adapter.java
> +		log.debug("Adapter [" + name + "] registered receiver [" + receiver.getName() + "] with properties [" + receiver + "]");
```suggestion
		if (log.isDebugEnabled()) log.debug("Adapter [" + name + "] registered receiver [" + receiver.getName() + "] with properties [" + receiver + "]");
```

2023-02-17 15:28 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/core/Adapter.java
> +		log.debug("Adapter [" + name + "] registered pipeline [" + pipeline + "]");
```suggestion
		if (log.isDebugEnabled()) log.debug("Adapter [" + name + "] registered pipeline [" + pipeline + "]");
```

2023-02-20 14:07 UTC, nielsm5 approved these changes

2023-02-20 15:41 UTC, gvanbrakel approved these changes

2023-02-20 16:34 UTC, merged