Convert more tests to use junit5
ibissource/iaf pull request #4536
Opened 2023-02-20 08:14 UTC by nielsm5

2023-02-21 12:09 UTC, gvanbrakel approved these changes

2023-02-22 14:58 UTC, tnleeuw requested changes

2023-02-22 14:58 UTC, tnleeuw commented on akamai/src/test/java/nl/nn/adapterframework/extensions/akamai/NetStorageCmsSignerTest.java
> +import org.junit.jupiter.api.Test;
Why not also import JUnit5 assertions?

2023-02-22 14:58 UTC, tnleeuw commented on core/src/test/java/nl/nn/adapterframework/xml/ClassLoaderURIResolverTest.java
> +import org.junit.jupiter.params.ParameterizedTest;
Import JUnit5 Assertions too, perhaps?

2023-02-22 14:58 UTC, tnleeuw commented on core/src/test/java/nl/nn/adapterframework/xml/ClassLoaderURIResolverTest2.java
> +import org.junit.jupiter.api.Test;
Importing JUnit5 Assertions too?

2023-02-22 14:58 UTC, tnleeuw commented on core/src/test/java/nl/nn/adapterframework/xml/SaxExceptionTest.java
> +import static org.junit.jupiter.api.Assertions.fail;
Import other assertions from JUnit5 package too, perhaps?

2023-02-24 10:05 UTC, tnleeuw approved these changes

2023-02-24 10:33 UTC, merged