Do backoff delay after instead off before failed msg processing
ibissource/iaf pull request #4643
Opened 2023-03-16 16:08 UTC by tnleeuw

2023-03-20 09:46 UTC, nielsm5 requested changes

2023-03-20 09:46 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +			exitWithoutProcessing = checkMessageHistory(rawMessageOrWrapper, message, messageId, businessCorrelationId, session, manualRetry, historyAlreadyChecked);
```suggestion
			boolean exitWithoutProcessing = checkMessageHistory(rawMessageOrWrapper, message, messageId, businessCorrelationId, session, manualRetry, historyAlreadyChecked);
```

2023-03-20 09:46 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +					Date receivedDate = PipeLineSession.getTsReceived(session);
```suggestion
					Date receivedDate = session.getTsReceived();
```

2023-03-20 09:46 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +		processResultCache.put(messageId, prci);
kan je hier niet beter een computeIfAbsent gebruiken?

2023-03-20 09:48 UTC, tnleeuw commented on copyrightExcludeFile.txt
> +.tlog
Oh, dat is zeker per ongeluk gecommit. Toen ik begon werden al die dingen nog niet goed in `target` gezet. Haal ik er zo weer uit.

2023-03-20 09:54 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
> +				}
Er werd een "altijd commit" gedaan ipv "commit of rollback" en dat kan voor een `UnexpectedRollbackException` zorgen (waarvoor Gerrit dan ergens anders weer een check had ingebakken in een TX manager class...).

Het leek mij netter om die commit/rollback hier expliciet uit te schrijven.

En ja het is een failsafe om te zorgen dat altijd de commit/rollback gedaan wordt voor de transactie die in deze method wordt aangemaakt. `Receiver.processRawMessage()` doet zelf geen commit/rollback van de transactie waarbinnen het bericht wordt aangemaakt.

2023-03-20 09:56 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +			log.error("{} Exception preparing to move input message with id [{}] correlationId [{}] to error sender", (Supplier<?>) this::getLogPrefix, (Supplier<?>) () -> originalMessageId, (Supplier<?>) ()
Vanwege de exception als laatste argument.

2023-03-20 10:07 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +		processResultCache.put(messageId, prci);
Ja, eigenlijk wel. Had ik niet aan gedacht!

2023-03-20 10:08 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
> +		if (errorSender==null && errorStorage==null) {
Is inderdaad niet mooi, ben ik met je eens. Wat jij voorstelt is toch wel netter ja.

2023-03-20 10:14 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaConfigurationBean.java
> +	}
Ik weet niet hoe dit erin is gekomen / gebleven. Had jij dit in deze branch toegevoegd ooit, toen jij ermee begon?

2023-03-22 13:48 UTC, tnleeuw commented on core/src/test/resources/testConfigurationContextWithTxManagers.xml
> +<beans xmlns="http://www.springframework.org/schema/beans"
Dat leek in eerste instantie niet te gaan maar ondertussen ziet de test-setup er alweer heel anders uit dan twee dagen geleden.
Ik kijk er nog een keer naar hoe dat te doen; er zit niet veel setup meer in de `setup()` method dus dat maakt het makkelijker.

2023-03-22 14:00 UTC, tnleeuw commented on iaf-commons/src/main/java/nl/nn/adapterframework/functional/FunctionalUtil.java
> +	}
Ah, korter...

`()->str` is korter dan `supply(str)` maar in de gevallen waarin ik nu `supply()` gebruik is de compiler niet tevreden met `()->str` en moet het worden `(Supplier<?>)()->x` om de compiler tevreden te houden en dat is weer langer. (En niet mooier).

Er was toch een reden dus waarom ik die functions had toegevoegd.

Zolang het gaat om `error` logs doe ik dan maar helemaal geen suppliers -- een error zal sowieso gelogd moeten worden, dat log-level zal waarschijnlijk nooit uitstaan.

2023-03-24 14:21 UTC, nielsm5 approved these changes

2023-03-24 14:58 UTC, merged