Fix Attributes on RootElements
ibissource/iaf pull request #4813
Opened 2023-04-21 15:24 UTC by nielsm5

2023-04-21 16:12 UTC, tnleeuw requested changes

2023-04-24 08:03 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/align/Properties2Xml.java
> +	public PropertyNode getRootNode(Map<String, String> container) {
Ja!

2023-04-24 14:55 UTC, tnleeuw approved these changes

2023-04-24 14:55 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/align/Json2Xml.java
> +				node = root.get(getRootElement());
I think that if this condition is false, then you won't reach this line b/c the above method would have thrown already?

2023-04-24 15:58 UTC, tnleeuw approved these changes

2023-04-25 09:06 UTC, merged