Preserve large messages to disk
ibissource/iaf pull request #4886
Opened 2023-05-13 08:01 UTC by tnleeuw

2023-05-13 08:56 UTC, nielsm5 commented
Ik wacht nog even met de review tot de andere pr's er door zijn om goed te kunnen zien wat er allemaal veranderd is.

2023-05-13 09:24 UTC, tnleeuw commented
> Ik wacht nog even met de review tot de andere pr's er door zijn om goed te kunnen zien wat er allemaal veranderd is.

Ja dat snap ik.

2023-05-15 15:52 UTC, nielsm5 requested changes

2023-05-15 15:52 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
> +				in.close();
Try with resources

2023-05-15 15:52 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
> +		Path destination = FileUtils.createTempFile().toPath();
Misschien is het mooi dit in een eigen folder te stoppen.

2023-05-16 07:22 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
> +	}
Kan eigenlijk ook wel weg, serialisation doet het zonder.

2023-05-16 09:16 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/stream/Message.java
> +	public static final long MESSAGE_MAX_IN_MEMORY_DEFAULT = 512L * 1024L;
Misschien dat 5mb toch een iets veiligere optie is...

2023-05-16 12:25 UTC, merged