Make Message return a MessageContext object
ibissource/iaf pull request #4979
Opened 2023-06-09 12:58 UTC by nielsm5

Ik zag in #4978 wat context dingen voorkomen en dacht laat ik maar gelijk een eerste stap maken..

2023-06-09 14:53 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/stream/Message.java
> +	public Message(String request, MessageContext context) {
Can we add `@Nonnullable` annotations to all these constructors as well, for the context at least?
(Perhaps also for the request, although there are some private constructors that do allow NULL request).

I would like at least context to never be NULL though and that is not guaranteed now.

2023-06-15 16:16 UTC, tnleeuw requested changes

2023-06-15 16:16 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/stream/Message.java
There's a null-check on messageContext in method `toStringPrefix()` which can now be removed as well.

2023-06-15 16:20 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/stream/Message.java
My silly Eclipse doesn't let me know about these things :(

2023-06-15 16:28 UTC, tnleeuw approved these changes

2023-06-15 16:38 UTC, merged