Create Sharable Resources
ibissource/iaf pull request #5050
Opened 2023-06-26 14:48 UTC by nielsm5

2023-06-28 11:51 UTC, tnleeuw requested changes

2023-06-28 11:51 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/core/CanShareResource.java
> +	void setSharedResourceName(String sharedResourceName);
Name `resourceReference` perhaps?

2023-06-28 13:17 UTC, nielsm5 commented on test/src/main/configurations/HTTP/Configuration.xml
> +		<ShareableResource name="SharedHttpSession" className="nl.nn.adapterframework.http.HttpSession"
JA! Maar dan moet ik eerst de Frank!Doc xsd lokaal updaten en omdat de naam nogal veel veranderd is de afgelopen 50 uur...

2023-06-28 13:18 UTC, nielsm5 commented on test/src/main/configurations/HTTP/Configuration.xml
> +	<ShareableResources>
SharedResources! Hier had ik het toevallig gisteren ook al over

2023-06-28 13:18 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java
> +		super.stop();
Omdat nu alle senders nog een open en close hebben ipv een start en stop :(

2023-06-29 13:37 UTC, tnleeuw approved these changes
Wat mij betreft goed, met een paar kleine suggesties.

2023-06-29 13:37 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/core/SharedWsdlDefinitions.java
>  	private Map<String, R> resources = new HashMap<>();
In plaats van hier een type-parameter `R` kan je ook de class `Definition` gebruiken, die uiteindelijk wordt gebruikt. En dan kan je de type-parameter weghalen uit de class-definitie.

2023-06-29 13:37 UTC, tnleeuw commented on core/src/test/java/nl/nn/adapterframework/configuration/digester/SharedResourceFactoryTest.java
> +	private static final String TEST_RESOURCE_VALUE = "mySharedDummyResource";
Ik zou de naam en de waarde verschillend maken zodat je zeker weet dat key-value nergens verward worden.

2023-06-30 13:08 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java
>  	}
Dat staat er boven :)

2023-06-30 15:54 UTC, merged

2023-07-01 08:04 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/core/SharedWsdlDefinitions.java
Eigenlijk is "WsdlCache" misschien wel een nog betere naam voor deze class. 🙈