Add an application log that also prints to the std-out
ibissource/iaf pull request #5256
Opened 2023-08-16 13:09 UTC by nielsm5

2023-08-21 10:09 UTC, Matthbo commented on core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java
> +			log("startup in " + startupTime + " ms");
Shouldn't this be like this as changed in other files in this pr
```suggestion
			log("startup in {} ms", startupTime);
```

2023-08-21 10:09 UTC, Matthbo commented on core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java
> +		log("shutdown in " + shutdownTime + " ms"); //Should log this before the actual Context is destroyed
Just like previous comment
```suggestion
		log("shutdown in {} ms", shutdownTime); //Should log this before the actual Context is destroyed
```

2023-08-21 13:47 UTC, philipsens approved these changes

2023-08-21 13:47 UTC, philipsens commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
> +			applicationLog.warn("unable to read pom.properties file for module[{}]", module, e);
That is the convention on capitalization?

2023-08-29 06:40 UTC, tnleeuw requested changes

2023-08-29 06:40 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
> +			applicationLog.fatal("IBIS WebApplicationInitializer failed to initialize", t);
Log naar zowel servlet-context en app. log

2023-08-29 06:40 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
>  		getServletContext().log("Shutting down IbisContext");
Log naar zowel servlet-context en app. log

2023-08-29 06:40 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java
>  			servletContext.log(String.format("%s, check ibis logs for more information! (%s) %s", msg, startupException.getClass().getName(), startupException.getMessage()));
Nog een log naar servlet context

2023-08-29 06:40 UTC, tnleeuw commented on core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationInitializer.java
> +			applicationLog.info(logLine);
Log naar zowel servlet-context en app. log

2023-08-29 13:16 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java
> +	private final Logger applicationLog = LogUtil.getLogger("APPLICATION");
Gelukkig is hier maar 1 object van, maar dat moeten we eigenlijk vaker doen ja!

2023-08-29 13:43 UTC, tnleeuw approved these changes

2023-08-29 13:56 UTC, Matthbo approved these changes

2023-08-29 15:29 UTC, merged