Components to typescript 2
ibissource/iaf pull request #5445
Opened 2023-09-22 10:15 UTC by Jarivanoort

2023-09-25 09:44 UTC, philipsens commented
Try to use short-lived branches. 

This means that you create a branch for a task and merge it when it is completed. The second task will get its own branch. 
This way, every branch is smaller and easier to review. 

The current PR is huge because you kept going from the old branch. So please keep in mind to create a new branch the next time.

2023-09-26 09:12 UTC, Matthbo commented
Squashed all the commits after the master squash merge commit and dropped it by rebase
Now to solve all merge conflicts

2023-09-27 14:05 UTC, Matthbo requested changes

2023-09-27 14:05 UTC, Matthbo commented on console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
> +            angular.element("select[name='type']").val(this.destinationTypes[0]);
`angular` is not gonna work when we remove angularjs, maybe try to make this with one-way binding on the actual element(s)

2023-09-27 15:29 UTC, Matthbo approved these changes

2023-09-28 09:15 UTC, merged