Update servicemix SAAJ
ibissource/iaf pull request #5665
Opened 2023-10-31 16:46 UTC by nielsm5

We need to figure out if we want to continue with SHA1 digests, newer versions seem to no longer support this.

2023-11-01 09:11 UTC, tnleeuw requested changes
Some tests now broken -- this needs to be fixed before we can proceed.


As discussed, we need to find another SAAJ implementation.

2023-11-02 19:50 UTC, tnleeuw commented
By updating also
```
		<dependency><!-- javax based dependency -->
			<groupId>jakarta.xml.soap</groupId>
			<artifactId>jakarta.xml.soap-api</artifactId>
			<version>3.0.1</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.activation</groupId>
					<artifactId>jakarta.activation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
from 1.4.2 to 3.0.1 in core/pom.xml the SAAJ lib will work in both JDK11 and JDK17, resolving almost all immediate JDK17 compatibility problems.

2023-11-04 18:00 UTC, nielsm5 commented
> By updating also
> 
> ```
> 		<dependency><!-- javax based dependency -->
> 			<groupId>jakarta.xml.soap</groupId>
> 			<artifactId>jakarta.xml.soap-api</artifactId>
> 			<version>3.0.1</version>
> 			<exclusions>
> 				<exclusion>
> 					<groupId>jakarta.activation</groupId>
> 					<artifactId>jakarta.activation-api</artifactId>
> 				</exclusion>
> 			</exclusions>
> 		</dependency>
> ```
> 
> from 1.4.2 to 3.0.1 in core/pom.xml the SAAJ lib will work in both JDK11 and JDK17, resolving almost all immediate JDK17 compatibility problems.

Not sure why we have this dependency but I rather fix the Java 17 issues in #5677.

2023-11-05 09:15 UTC, tnleeuw approved these changes

2023-11-05 11:16 UTC, merged