Upgrade JBoss Docker image to 7.4.13-7
ibissource/iaf pull request #5704
Opened 2023-11-07 16:37 UTC by philipsens

2023-11-07 17:11 UTC, nielsm5 approved these changes

2023-11-07 17:24 UTC, tnleeuw requested changes
Werkt alleen nog niet helemaal helaas, lijkt het!

```
17:58:54  java.lang.IllegalStateException: WFLYSRV0126: Could not create server content directory: /opt/eap/standalone/data/content
17:58:54  	at org.jboss.as.server@15.0.30.Final-redhat-00001//org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:534)
17:58:54  	at org.jboss.as.server@15.0.30.Final-redhat-00001//org.jboss.as.server.Main.determineEnvironment(Main.java:425)
17:58:54  	at org.jboss.as.server@15.0.30.Final-redhat-00001//org.jboss.as.server.Main.main(Main.java:97)
17:58:54  	at org.jboss.modules.Module.run(Module.java:353)
17:58:54  	at org.jboss.modules.Module.run(Module.java:321)
17:58:54  	at org.jboss.modules.Main.main(Main.java:620)
17:58:54  17:58:52,661 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
```

Dat moet nog even worden gefixed... 😳

2023-11-07 18:33 UTC, tnleeuw requested changes
Bijna bijna bijna!

Maar nog niet helemaal.

De logs worden nog niet goed gedownload:

```
19:04:51  Compress /home/jboss/jboss-eap-7.3/standalone/log to /home/jenkins/agent/workspace/ff-ci/larva/16120-larva-logs.zip
```

En de log-zip artifacts in Jenkins zijn leeg (zie: https://jenkins.frankframework.org/job/ff-ci/job/larva/16120/ ).

Maar dat zit in de CI geloof ik en niet in dit PR? Als dat zo is dan approve ik dit PR ook.

2023-11-08 09:16 UTC, philipsens commented
> Bijna bijna bijna!
> 
> Maar nog niet helemaal.
> 
> De logs worden nog niet goed gedownload:
> 
> ```
> 19:04:51  Compress /home/jboss/jboss-eap-7.3/standalone/log to /home/jenkins/agent/workspace/ff-ci/larva/16120-larva-logs.zip
> ```
> 
> En de log-zip artifacts in Jenkins zijn leeg (zie: https://jenkins.frankframework.org/job/ff-ci/job/larva/16120/ ).
> 
> Maar dat zit in de CI geloof ik en niet in dit PR? Als dat zo is dan approve ik dit PR ook.

Goed gezien!

De CI is aangepast om de logs nu wel goed op te slaan!

2023-11-08 10:10 UTC, tnleeuw approved these changes

2023-11-08 10:29 UTC, nielsm5 approved these changes

2023-11-08 10:29 UTC, merged